### ISSUE TITLE
Download failed: https://ghcr.io/v2/shivammathur/php/php/8.1/manifests/8.1.0_3-22

### ISSUE THREAD

**Issue by denguyen-tvit** [shivammathur/homebrew-php#1015]
**Describe the bug**
Currently, can not install shivammathur/php/php@8.1

==> Downloading https://ghcr.io/v2/shivammathur/php/php/8.1/manifests/8.1.0_3-22
##O#- #                                                                       
curl: (22) The requested URL returned error: 404 
Error: php@8.1: Failed to download resource "php@8.1_bottle_manifest"
Download failed: https://ghcr.io/v2/shivammathur/php/php/8.1/manifests/8.1.0_3-22
**Screenshots/Logs**
<img width="1099" alt="Screen Shot 2022-08-18 at 22 27 01" src="https://user-images.githubusercontent.com/21253586/185433856-74611b04-594f-4a78-9136-d52a71852380.png">
**Additional context**
Mac OS 10.15.6 (19G73)

**Comment by shivammathur** [comment]
Please run `brew update` and try installing again.
