### ISSUE TITLE
Emergency Update with icu4c

### ISSUE THREAD

**Issue by jyxjjj** [shivammathur/homebrew-php#1068]
**Describe the bug**
icu4c from brew has been updated to 71 then php requesting to use 70

so it will broken with

```
dyld[28892]: Library not loaded: '/opt/homebrew/opt/icu4c/lib/libicuio.70.dylib'
  Referenced from: '/opt/homebrew/Cellar/php/8.1.10/bin/php'
  Reason: tried: '/opt/homebrew/opt/icu4c/lib/libicuio.70.dylib' (no such file), '/usr/local/lib/libicuio.70.dylib' (no such file), '/usr/lib/libicuio.70.dylib' (no such file), '/opt/homebrew/Cellar/icu4c/71.1/lib/libicuio.70.dylib' (no such file), '/usr/local/lib/libicuio.70.dylib' (no such file), '/usr/lib/libicuio.70.dylib' (no such file)
```

**PHP versions**
7.3 7.4 8.0 8.1 and maybe more

**To Reproduce**
`brew update && brew upgrade`

**Expected behavior**
`php -v`
`php 8.1.10`

**Screenshots/Logs**
N/A

**Additional context**
N/A

**Are you willing to submit a PR?**
I don't know how to (for brews).

**Comment by jyxjjj** [comment]
![image](https://user-images.githubusercontent.com/16695261/188559075-2568b888-ab63-4e12-920d-84c4feb7968d.png)
![image](https://user-images.githubusercontent.com/16695261/188559110-a250af0d-04f1-40ae-a56e-a0e74500c21d.png)
![image](https://user-images.githubusercontent.com/16695261/188559137-13fba718-a5ac-4301-b989-f3261b89c786.png)

**Comment by jyxjjj** [comment]
I searched Google that i found a lot of dependence error with this package.
I think it is not your fault and am very glad to use your package, it fixed that official PHP package doesn't support ARM64.


To temporary fix this error:

```
cd /opt/homebrew/Library/Taps/homebrew/homebrew-core/Formula
curl -O https://raw.githubusercontent.com/Homebrew/homebrew-core/fe6a2fe48c2abd7aee0636a5d25d9cdb7374686a/Formula/icu4c.rb
brew reinstall icu4c
brew pin icu4c
git restore icu4c.rb
brew update && brew upgrade
```

**Comment by jyxjjj** [comment]
![image](https://user-images.githubusercontent.com/16695261/188592379-9f133c91-6132-4163-a7cf-6c9a4c87d6c3.png)


Ahhhhh, And i think these 4 issues are the same too. lol.

**Comment by shivammathur** [comment]
Working on this

**Comment by shivammathur** [comment]
@jyxjjj 

All PHP formulae are now rebuilt with icu4c 71.1

If you get a `Library not loaded` error for `icu4c` libraries.
Please update the tap and upgrade the PHP formula.

For example for `PHP 8.0`.

```zsh
brew update 
brew upgrade shivammathur/php/php@8.0
```

Please do not pin the icu4c version from older commits.
