### ISSUE TITLE
php5.6 mcrypt is missing

### ISSUE THREAD

**Issue by aiwozhe** [shivammathur/homebrew-php#1159]
**Describe the bug**

php5.6 mcrypt is missing

**PHP versions**

php5.6.40_5

**To Reproduce**

**Expected behavior**

**Screenshots/Logs**

**Additional context**

**Are you willing to submit a PR?**

**Comment by shivammathur** [comment]
Please use [`shivammathur/extensions`](https://github.com/shivammathur/homebrew-extensions) tap for mcrypt.

```zsh
brew tap shivammathur/extensions
brew install shivammathur/extensions/mcrypt@5.6
```
