### ISSUE TITLE
pecl for 7.1

### ISSUE THREAD

**Issue by glensc** [shivammathur/homebrew-php#1210]
**Describe the bug**

`/opt/homebrew/opt/php@7.1/pecl` points to `/opt/homebrew/lib/php/pecl` which points to latest PHP, so installing pecl packages results:
1. installation failure as symlink points to nowhere
2. installation to wrong PHP version

**PHP versions**

7.1

**To Reproduce**

```
brew install shivammathur/php/php@7.1
/opt/homebrew/opt/php@7.1/bin/pecl install xdebug-2.9.8
```

**Expected behavior**

**Screenshots/Logs**

**Additional context**

I think this simple fix solves the problem:

```
lrwxr-xr-x 1 glen admin 7 Oct  4 11:21 /opt/homebrew/opt/php@7.1/pecl -> lib/php/
```

i.e make "pecl" symlink to "lib/php"

**Are you willing to submit a PR?**

**Comment by shivammathur** [comment]
Please link the PHP version after installing it. It should work correctly.
https://github.com/shivammathur/homebrew-php#install-php

Test workflow: https://github.com/shivammathur/test-setup-php/actions/runs/3180798502/workflow

**Comment by glensc** [comment]
I do not want to link, my linked php is different version. how about the symlink change proposal? it's wrong anyway to point to the unversioned default php (`/opt/homebrew/lib/php/pecl`).

**Comment by glensc** [comment]
can you show where does the `pecl` symlink points before and after the link of 7.1:

```
ls -ld /usr/local/Cellar/php@7.1/7.1.33_5/pecl
```

**Comment by glensc** [comment]
Tried to add debug:
- https://github.com/shivammathur/test-setup-php/pull/4

but the actions are not run because I'm new contributor?

**Comment by shivammathur** [comment]
The symlink in the cellar points to `$(brew --prefix)/lib/php/pecl` both before and after linking.
https://github.com/shivammathur/test-setup-php/actions/runs/3182403244/jobs/5188302224#step:4:96

The pecl directory in lib  `$(brew --prefix)/lib/php/pecl` is not the default php's directory. It is the parent directory that has the subdirectories for extensions of each PHP version. For example it will be `$(brew --prefix)/lib/php/pecl/20210902` for `PHP 8.1`.

If you want how PHP symlinks are created changed, please create an issue/PRs on the [core tap](https://github.com/Homebrew/homebrew-core). If it is changed there, I will sync it here.

**Comment by glensc** [comment]
I don't have that directory:

```
➜ ls -l $(brew --prefix)/lib/php/pecl
ls: cannot access '/opt/homebrew/lib/php/pecl': No such file or directory
```

that directory build is unversioned and points to latest php:

```
✖  ls -l $(brew --prefix)/lib/php
total 0
lrwxr-xr-x 1 glen admin 42 Sep  7 12:16 20210902 -> ../../Cellar/php/8.1.10_1/lib/php/20210902/
lrwxr-xr-x 1 glen admin 39 Sep  7 12:16 build -> ../../Cellar/php/8.1.10_1/lib/php/build/
```

indeed it makes sense that `$(brew --prefix)/lib/php/pecl/20160303` would be outside php@7.1 cellar, as otherwise if php@7.1 is upgraded, all extensions installed with pecl will need to be re-installed.

so problem with my setup is, why is `$(brew --prefix)/lib/php/pecl` missing, how it should have been created?

**Comment by glensc** [comment]
missing (broken link) for all php versions, 7.1 i hacked symlink myself:

```
➜ ls -ld /opt/homebrew/Cellar/php*/*/pecl
lrwxr-xr-x 1 glen admin 26 Sep  7 12:16 /opt/homebrew/Cellar/php/8.1.10_1/pecl -> /opt/homebrew/lib/php/pecl
lrwxr-xr-x 1 glen admin  7 Oct  4 11:21 /opt/homebrew/Cellar/php@7.1/7.1.33_5/pecl -> lib/php/
lrwxr-xr-x 1 glen admin 26 Sep  7 12:15 /opt/homebrew/Cellar/php@7.4/7.4.30_1/pecl -> /opt/homebrew/lib/php/pecl
lrwxr-xr-x 1 glen admin 26 Sep  7 12:15 /opt/homebrew/Cellar/php@8.0/8.0.23_1/pecl -> /opt/homebrew/lib/php/pecl
```

i think each of those php formulas should ensure the shared directory exist, but none of them seem to have such code:
- https://github.com/Homebrew/homebrew-core/blob/e8477fa641c181665348e194d11752d2a12c08ec/Formula/php.rb
- https://github.com/Homebrew/homebrew-core/blob/e8477fa641c181665348e194d11752d2a12c08ec/Formula/php%407.4.rb
- https://github.com/Homebrew/homebrew-core/blob/e8477fa641c181665348e194d11752d2a12c08ec/Formula/php%408.0.rb

**Comment by glensc** [comment]
reported to homebrew core:
- https://github.com/Homebrew/homebrew-core/issues/112329

**Comment by glensc** [comment]
Fixed with re-running postinstall:
- https://github.com/Homebrew/homebrew-core/issues/112329#issuecomment-1268096041
