### ISSUE TITLE
/usr/sbin/apachectl: line 92: 14394 Segmentation fault: 11  $HTTPD "$@"

### ISSUE THREAD

**Issue by lengnuan-v** [shivammathur/homebrew-php#1279]
[Tue Oct 25 16:34:17.217497 2022] [so:notice] [pid 14394] AH06662: Allowing module loading process to continue for module at /usr/local/opt/php@5.6/lib/httpd/modules/libphp5.so because module signature matches authority "PHP" specified in LoadModule directive
httpd not running, trying to start
/usr/sbin/apachectl: line 92: 14394 Segmentation fault: 11  $HTTPD "$@"

**Comment by lengnuan-v** [comment]
PHP VERSION 8.0, 7.4, 5.6 IS INSTALLED. Switching TO VERSION 5.6 WILL CAUSE AN ERROR

**Comment by shivammathur** [comment]
Please use `httpd` from brew instead of system apache.
https://getgrav.org/blog/macos-monterey-apache-multiple-php-versions
