### ISSUE TITLE
Cannot Switch To PHP 8.1

### ISSUE THREAD

**Issue by benbelmour** [shivammathur/homebrew-php#1340]
**Describe The Bug**
I cannot switch to PHP 8.1.

**PHP Versions**
Upgrading from PHP 8.0 to PHP 8.1.

**To Reproduce**
- Open Terminal
- Type: `php -v`
- Output: PHP 8.0.25
- Type: `brew link --overwrite --force shivammathur/php/php@8.1`
- Restart Terminal
- Type: `php -v`
- Output: PHP 8.0.25

**Expected Behavior**
PHP should switch to version 8.1.

**Screenshots/Logs**

<img width="587" alt="image" src="https://user-images.githubusercontent.com/79989595/201080424-4da2964d-8c6c-4c7c-a7ac-3e06a7e9e333.png">
<img width="588" alt="image" src="https://user-images.githubusercontent.com/79989595/201080530-aad7185c-2876-4a98-9506-3a737cb05be8.png">

**Comment by shivammathur** [comment]
Please remove `/usr/local/opt/php@8.0/bin` and `/usr/local/opt/php@8.0/sbin` from your PATH. The only locations you need are `/usr/local/bin` and `/usr/local/sbin` which are there in your PATH and brew links the PHP version in those locations.
