### ISSUE TITLE
php@8.1 has incompatible Api Version for loading extensions

### ISSUE THREAD

**Issue by boesing** [shivammathur/homebrew-php#1425]
**Describe the bug**
When I install extensions via `pecl`, the last step of the installation is adding the extension to `php.ini`. This is done by i.e. adding `extension=igbinary.so`

When using `php@8.1`, I can only load extensions using absolute path pointing to the proper pecl directory of my installed PHP version. The relativ path tries to load it from the `php@8.0` directory. Since I do have that directory as well, the error which is displayed is:

```
PHP Warning:  PHP Startup: igbinary: Unable to initialize module
Module compiled with module API=20201009
PHP    compiled with module API=20210902
These options need to match
 in Unknown on line 0
```

**PHP versions**
PHP 8.1 & PHP 8.2

**To Reproduce**

- install `php@8.1` or `php@8.2`
- use `pecl` to install `igbinary` extension
- wait until installations says: Build process completed successfully [...] Installing '/usr/local/Cellar/php@8.1/8.1.13/pecl/20210902/igbinary.so'
- double check `php.ini` to contain `extension=igbinary.so` (`/usr/local/etc/php/8.1/php.ini`)
- run `php -m` and see that igbinary is not available plus getting the error mentioned above

**Expected behavior**

Both PHP 8.1 & PHP 8.2 are properly configured to use pecl module API version of its version.

As of now, it seems that PHP 8.1 uses PHP 8.0 Module API Version and PHP 8.2 uses PHP 8.1 Module API version. So as if these versions are lagging behind 1 version.

**Screenshots/Logs**

```
→ /usr/local/bin/php --version
PHP Warning:  PHP Startup: Unable to load dynamic library 'redis.so' (tried: /usr/local/lib/php/pecl/20210903/redis.so (dlopen(/usr/local/lib/php/pecl/20210903/redis.so, 0x0009): tried: '/usr/local/lib/php/pecl/20210903/redis.so' (no such file)), /usr/local/lib/php/pecl/20210903/redis.so.so (dlopen(/usr/local/lib/php/pecl/20210903/redis.so.so, 0x0009): tried: '/usr/local/lib/php/pecl/20210903/redis.so.so' (no such file))) in Unknown on line 0

Warning: PHP Startup: Unable to load dynamic library 'redis.so' (tried: /usr/local/lib/php/pecl/20210903/redis.so (dlopen(/usr/local/lib/php/pecl/20210903/redis.so, 0x0009): tried: '/usr/local/lib/php/pecl/20210903/redis.so' (no such file)), /usr/local/lib/php/pecl/20210903/redis.so.so (dlopen(/usr/local/lib/php/pecl/20210903/redis.so.so, 0x0009): tried: '/usr/local/lib/php/pecl/20210903/redis.so.so' (no such file))) in Unknown on line 0
PHP Warning:  PHP Startup: Unable to load dynamic library 'igbinary.so' (tried: /usr/local/lib/php/pecl/20210903/igbinary.so (dlopen(/usr/local/lib/php/pecl/20210903/igbinary.so, 0x0009): tried: '/usr/local/lib/php/pecl/20210903/igbinary.so' (no such file)), /usr/local/lib/php/pecl/20210903/igbinary.so.so (dlopen(/usr/local/lib/php/pecl/20210903/igbinary.so.so, 0x0009): tried: '/usr/local/lib/php/pecl/20210903/igbinary.so.so' (no such file))) in Unknown on line 0

Warning: PHP Startup: Unable to load dynamic library 'igbinary.so' (tried: /usr/local/lib/php/pecl/20210903/igbinary.so (dlopen(/usr/local/lib/php/pecl/20210903/igbinary.so, 0x0009): tried: '/usr/local/lib/php/pecl/20210903/igbinary.so' (no such file)), /usr/local/lib/php/pecl/20210903/igbinary.so.so (dlopen(/usr/local/lib/php/pecl/20210903/igbinary.so.so, 0x0009): tried: '/usr/local/lib/php/pecl/20210903/igbinary.so.so' (no such file))) in Unknown on line 0
PHP 8.2.0-dev (cli) (built: Oct  7 2022 01:00:04) (NTS)
Copyright (c) The PHP Group
Zend Engine v4.2.0-dev, Copyright (c) Zend Technologies
    with Zend OPcache v8.2.0-dev, Copyright (c), by Zend Technologies
```

```
→ /usr/local/bin/php --version
PHP Warning:  PHP Startup: redis: Unable to initialize module
Module compiled with module API=20201009
PHP    compiled with module API=20210902
These options need to match
 in Unknown on line 0

Warning: PHP Startup: redis: Unable to initialize module
Module compiled with module API=20201009
PHP    compiled with module API=20210902
These options need to match
 in Unknown on line 0
PHP Warning:  PHP Startup: igbinary: Unable to initialize module
Module compiled with module API=20201009
PHP    compiled with module API=20210902
These options need to match
 in Unknown on line 0

Warning: PHP Startup: igbinary: Unable to initialize module
Module compiled with module API=20201009
PHP    compiled with module API=20210902
These options need to match
 in Unknown on line 0
PHP 8.1.13 (cli) (built: Dec  9 2022 16:26:34) (NTS)
Copyright (c) The PHP Group
Zend Engine v4.1.13, Copyright (c) Zend Technologies
    with Zend OPcache v8.1.13, Copyright (c), by Zend Technologies
    with Xdebug v3.1.2, Copyright (c) 2002-2021, by Derick Rethans

```

**Additional context**

-
**Are you willing to submit a PR?**

Yes, but I have not that deep knowledge of PHP compilation and stuff and I guess that this is probably more related to the php-builder?

**Comment by boesing** [comment]
I am not 100% sure if this is the case but I found out that I do actually have multiple (different) PHP versions of the same PHP version installed:

| PHP | Path                         | Path 2                           |
|-----|------------------------------|----------------------------------|
| 8.2 | /usr/local/Cellar/php/8.2.0  | /usr/local/Cellar/php@8.2/8.2.0  |
| 8.1 | /usr/local/Cellar/php/8.1.11 | /usr/local/Cellar/php@8.1/8.1.13 |

The `php@8.2` path is gone since the latest update (I guess due to the fact that now `php` is `8.2` but for `8.1` I still have both directories available).

Since there are two different install paths, I guess some scripts are getting confused. Maybe some changes in this repository led to the fact that there are multiple paths and old paths are not getting cleaned up after the changes.

I had to re-link `php` to actually update some links to point to the proper Cellar directory, prior re-linking, `/usr/local/opt/php@8.1` was linked to the `8.1.11` directory even tho the `8.1.13` directory existed.
Same for the PHP 8.2 version which still linked to a `8.2.0-dev` version from October.

Maybe all these directory stuff led to the invalid PHP API versions when compiling `pecl` packages. I will double check that again now that I fixed the symlinks.

**Comment by boesing** [comment]
> Maybe all these directory stuff led to the invalid PHP API versions when compiling `pecl` packages. I will double check that again now that I fixed the symlinks.

Hm nope, the error still occurs even after force re-installing the extensions.

**Comment by shivammathur** [comment]
@boesing If you are still facing this issue, I would advise reinstalling everything, including extensions installed using PECL.
Also make sure you remove the ini files for the PHP version in $(brew --prefix)/etc/php/
