### ISSUE TITLE
No more pecl since last big sur update on M1 chipset

### ISSUE THREAD

**Issue by thibmonier** [shivammathur/homebrew-php#144]
**Describe the bug**

Since last big sur update and homebrew update, php7.4 always return killed 
it seems that php as broken links with pecl.
The result is any command return killed
$> php -v 
Killed

**PHP versions**

Php7.4 (and others maybe)

**To Reproduce**

**Expected behavior**

**Screenshots/Logs**

run any php cmd
![image](https://user-images.githubusercontent.com/413136/108038641-61230b00-703b-11eb-83a8-b211b75f6f30.png)
install php@7.4
![image](https://user-images.githubusercontent.com/413136/108038937-b9f2a380-703b-11eb-8286-0bfa20402cce.png)

**Additional context**

**Are you willing to submit a PR?**

**Comment by shivammathur** [comment]
I cannot reproduce the issue on my end.
Can you please reinstall PHP 7.4 and see if it works correctly.

```zsh
# Remove PHP and any PHP services that may exist
brew remove php@7.4
sudo rm -f ~/Library/LaunchAgents/homebrew.mxcl.php*
sudo rm -f /Library/LaunchAgents/homebrew.mxcl.php*
sudo rm -f /Library/LaunchDaemons/homebrew.mxcl.php*

# Update brew and shivammathur/php tap
HOMEBREW_DEVELOPER=1 brew untap shivammathur/php
brew tap shivammathur/php
brew update

# Install PHP 7.4
brew install shivammathur/php/php@7.4
brew link --force --overwrite php@7.4
```

Restart terminal and check PHP
```zsh
php -v
```

**Comment by thibmonier** [comment]
I did it several times, and each times I had this result
![image](https://user-images.githubusercontent.com/413136/108042478-1f489380-7040-11eb-8faf-c3722f31291b.png)
After some research, I saw that pecl is no more installed but symbolic links are still there

**Comment by shivammathur** [comment]
Run this 
```
sudo rm -rf /opt/homebrew/lib/php
sudo rm -rf $(brew --cellar php)
```
and then reinstall PHP

**Comment by thibmonier** [comment]
still the same result : 
- symbolic links are dead
- php return killed

**Comment by shivammathur** [comment]
I upgraded to `Big Sur 11.2.1` and still cannot reproduce the issue.
Something is not right with your PHP or brew setup. 
There is no issue with this tap.

Reinstall brew and try installing PHP again
```
sudo rm -rf /opt/hombrew
/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install.sh)"
brew update
brew tap shivammathur/php
brew install shivammathur/php/php@7.4
brew link --force --overwrite php@7.4
```
