### ISSUE TITLE
Cannot Switch PHP Versions

### ISSUE THREAD

**Issue by jmcgrory** [shivammathur/homebrew-php#1460]
**Describe the bug**

Once I've linked one PHP version, I've been unable to switch to another, regardless of following the troubleshooting in the README.

**PHP versions**

 - 7.4
 - 8.0  
 - 8.1  

**To Reproduce**

 1. `brew install shivammathur/php/php@7.4`  
 2. `brew link --overwrite --force shivammathur/php/php@7.4`  
 3. `php -v`  
     - ```PHP 7.4.33 (cli) (built: Dec  8 2022 21:24:25) ( NTS )```  
 4. `brew install shivammathur/php/php@8.1`  
 5. `brew link --overwrite --force shivammathur/php/php@8.1`  
 6. `php -v`  
     - ```PHP 7.4.33 (cli) (built: Dec  8 2022 21:24:25) ( NTS )```

This is regardless of:  

 - Unlinking PHP versions  
 - Forcing/Not Forcing  
 - Restarting the service  
 - Reopening the terminal  

**Expected behavior**

To be able to switch between versions.

**Additional context**

MacOS Monterey 12.5.1

**Comment by jmcgrory** [comment]
My current solution is to literally remove each formulae after using at this point, which as you can imagine is quite annoying.

**Comment by shivammathur** [comment]
Please check your `$PATH`, if you have the bin directory for a specific PHP version in your `$PATH`, please remove that, you only need brew's bin directory `$(brew --prefix)/bin` in there.
