### ISSUE TITLE
Error: Unable to build httpd from source with HOMEBREW_INSTALL_FROM_API.

### ISSUE THREAD

**Issue by elburro1887** [shivammathur/homebrew-php#1515]
**Describe the bug**
Cant install any of the php versions due to httpd issue:

```
brew install shivammathur/php/php@8.0
==> Fetching dependencies for shivammathur/php/php@8.0: httpd, freetds, cmake and highway
==> Fetching httpd
Error: Unable to build httpd from source with HOMEBREW_INSTALL_FROM_API.
```
Could maybe be related to the new Homebrew version? I'm on Homebrew 3.6.20-72-g8f41918

**PHP versions**
Tested with 7.2, 7.3, 8.0, 8.1

**To Reproduce**
brew install shivammathur/php/php@8.0

**Comment by elburro1887** [comment]
So I managed to fix the issue by exporting the appropriate env setting before running the install.

`export HOMEBREW_NO_INSTALL_FROM_API=1`

This makes brew install the packages from source instead of using their new API.

Please close this issue.

**Comment by shivammathur** [comment]
You can also run `brew install -s <formula>` to install from the source.
