### ISSUE TITLE
Versioned Formula is blocking re-install or fresh install

### ISSUE THREAD

**Issue by sschueller** [shivammathur/homebrew-php#1560]
**Describe the bug**
The line https://github.com/shivammathur/homebrew-php/blob/master/Formula/php%407.4.rb#L26 casues ```brew install php@7.4``` to fail with: ```Error: php@7.4 has been disabled because it is a versioned formula!```

**PHP versions**
7.4 (did not test others)

**To Reproduce**
```brew install php@7.4```

**Work around***
```brew install shivammathur/php/php@7.4```
Will show: Warning: shivammathur/php/php@7.4 has been deprecated because it is a versioned formula!

**Expected behavior**
For installation to complete

**Screenshots/Logs**
```Error: php@7.4 has been disabled because it is a versioned formula!```

**Additional context**
N/A

**Are you willing to submit a PR?**
Possibly if I can get it to work

**Comment by shivammathur** [comment]
@sschueller 

`php@7.4` still exists in `homebrew-core` tap. So brew tries installing it from there when you run `brew install php@7.4`. As it is disabled there, you get the error.
https://github.com/Homebrew/homebrew-core/blob/master/Formula/php@7.4.rb#L23

For using the formula from this tap, It is advised to always use the full qualified formula name i.e. `shivammathur/php/php@7.4`.
https://github.com/shivammathur/homebrew-php#install-php

For this issue to be fixed the disabled formula should be removed from the core tap. Please raise this issue [there](https://github.com/Homebrew/homebrew-core/issues).
