### ISSUE TITLE
PHP8.0.28 Can't execute "phpinfo" command, it gets stuck

### ISSUE THREAD

**Issue by cevin** [shivammathur/homebrew-php#1574]
**Describe the bug**
![image](https://user-images.githubusercontent.com/338110/218936682-6d839d44-b262-418c-8575-032a529791bb.png)

**PHP versions**
```
PHP 8.0.28 (cli) (built: Feb 14 2023 15:42:52) ( NTS )
Copyright (c) The PHP Group
Zend Engine v4.0.28, Copyright (c) Zend Technologies
    with Zend OPcache v8.0.28, Copyright (c), by Zend Technologies
```
**To Reproduce**
`/path/bin/php -r "phpinfo();"`

**Screenshots/Logs**
![image](https://user-images.githubusercontent.com/338110/218936682-6d839d44-b262-418c-8575-032a529791bb.png)

**Additional context**
installed extensions:
```
[PHP Modules]
bcmath
bz2
calendar
Core
ctype
curl
date
dba
dom
exif
FFI
fileinfo
filter
ftp
gd
gettext
gmp
hash
iconv
igbinary
imagick
intl
json
ldap
libxml
mbstring
msgpack
mysqli
mysqlnd
odbc
openssl
pcntl
pcre
PDO
pdo_dblib
pdo_mysql
PDO_ODBC
pdo_pgsql
pdo_sqlite
pgsql
Phar
phpdbg_webhelper
posix
pspell
readline
redis
Reflection
session
shmop
SimpleXML
soap
sockets
sodium
SPL
sqlite3
standard
swoole
sysvmsg
sysvsem
sysvshm
tidy
tokenizer
xml
xmlreader
xmlwriter
xsl
Zend OPcache
zip
zlib

[Zend Modules]
Zend OPcache
```

**Are you willing to submit a PR?**
No

**Comment by shivammathur** [comment]
It should not get stuck but surely it takes longer to run if you have `imagick` extension. Please test by removing the extension and running `phpinfo`. This issue is not related to PHP.
