### ISSUE TITLE
Could not get iconv in php 8.0 on mac os

### ISSUE THREAD

**Issue by sashabeep** [shivammathur/homebrew-php#1616]
```
Root composer.json requires linked library lib-iconv * but it has the wrong version installed or is missing from your system, make sure to load the extension providing it.
```
phpinfo
```
iconv support => enabled
iconv implementation => unknown
iconv library version => unknown
```
Tried ro install iconv with brew but nothing changed. What i should do?

**Comment by shivammathur** [comment]
Iconv is compiled statically into php.
Ref: https://github.com/shivammathur/homebrew-php/blob/master/Formula/php.rb#L156

Test: https://github.com/shivammathur/test-setup-php/actions/runs/4667582166
