### ISSUE TITLE
Installing php@7.2 from shivammathur/php install error

### ISSUE THREAD

**Issue by dorisnzy** [shivammathur/homebrew-php#1632]
brew install shivammathur/php/php@7.2

Warning: You are using macOS 13.
We do not provide support for this pre-release version.
You will encounter build failures with some formulae.
Please create pull requests instead of asking for help on Homebrew's GitHub,
Twitter or any other official channels. You are responsible for resolving
any issues you experience while you are running this
pre-release version.

==> Installing php@7.2 from shivammathur/php
Warning: shivammathur/php/php@7.2 has been deprecated because it is deprecated upstream!
Error: bison: no bottle available!
You can try to install from source with:
  brew install --build-from-source bison
Please note building from source is unsupported. You will encounter build
failures with some formulae. If you experience any issues please create pull
requests instead of asking for help on Homebrew's GitHub, Twitter or any other
official channels.

**Comment by shivammathur** [comment]
Please run the following commands

```
brew update
```

then run this, and if it reports any errors fix them.
```
brew doctor
```

Then try installing again.
