### ISSUE TITLE
Temnam(): file created in the system's temporary directory

### ISSUE THREAD

**Issue by zieru** [shivammathur/homebrew-php#1709]
**Describe the bug**
I can't install laravel, because tempnam error

**PHP versions**
8.2.4

**To Reproduce**
Composer install
(laravel project)

**Expected behavior**

**Screenshots/Logs**
tempnam(): file created in the system's temporary directory

**Comment by shivammathur** [comment]
This is not an error, but a notice that it used the system's temporary directory as the fallback for create a temporary file.
Please ask this question on StackOverflow.
