### ISSUE TITLE
icu4c version mismatch

### ISSUE THREAD

**Issue by HapiCZ** [shivammathur/homebrew-php#174]
**Describe the bug**
I don't know if this is a formula or PHP problem:

Homebrew now contains icu4c in version 68.2 but php (tried 7.3, 7.4, 8.0) dependents on versio 67.1.

```
➜  ~ php
dyld: Library not loaded: /usr/local/opt/icu4c/lib/libicuio.67.dylib
  Referenced from: /usr/local/opt/php@7.4/bin/php
  Reason: image not found
[1]    27004 abort      php
```

**PHP versions**
7.3, 7.4, 8.0

**To Reproduce**
Uninstall all php versions
Upgrade icu4c
Install php

** Temporary solution **
Manualy downgrade icu4c

example:
https://www.javaer101.com/en/article/7047493.html

**Comment by atomiix** [comment]
Another temporary solution is to build from sources

**Comment by shivammathur** [comment]
Working on a fix, I need to first patch [shivammathur/setup-php](https://github.com/shivammathur/setup-php) before I run upgrade here.

**Comment by shivammathur** [comment]
Updated. ICU version should now be `68.2`.

Before installing please fetch the tap again.
```zsh
HOMEBREW_DEVELOPER=1 brew untap shivammathur/php
brew tap shivammathur/php
```

**Comment by HapiCZ** [comment]
tested and working... thank you for really fast fix

**Comment by heidilux** [comment]
Hiya, 
Is it possible this same issue has cropped up again, with mismatched versions? The installed icu4c version is now 71, while a php command errors out saying it can't find v69.
