### ISSUE TITLE
Installing php@7.0 from shivammathur/php install error

### ISSUE THREAD

**Issue by parvez3019** [shivammathur/homebrew-php#1798]
Getting the following error while installing php@7.0

brew install shivammathur/php/php@7.0

==> Downloading https://ghcr.io/v2/homebrew/core/libzip/blobs/sha256:d6c764255ed4b3350cace110c8a6e1f37fb512cf38c7dc1809b2ae66c
==> Downloading from https://pkg-containers.githubusercontent.com/ghcr1/blobs/sha256:d6c764255ed4b3350cace110c8a6e1f37fb512cf3
curl: (56) Recv failure: Operation timed out      #         #        #

Error: php@7.0: Failed to download resource "libzip"
Download failed: https://ghcr.io/v2/homebrew/core/libzip/blobs/sha256:d6c764255ed4b3350cace110c8a6e1f37fb512cf38c7dc1809b2ae66c0cc5a40

**Comment by shivammathur** [comment]
@parvez3019 

Please run `brew update` and then try again.

If it still not working, try running `brew doctor` and check if it reports any issues.
