### ISSUE TITLE
php7.3 without enable dblib

### ISSUE THREAD

**Issue by bphmigas** [shivammathur/homebrew-php#1823]
how to install php ver 7.3 without installing or enable dblib freetds extension?

**Comment by shivammathur** [comment]
The extension is compiled statically into the php binary in the formula. 

You can remove this line from the formula and install it from the source without the extension.
https://github.com/shivammathur/homebrew-php/blob/master/Formula/php%407.3.rb#L164

Edit the formula and remove the line
```zsh
brew edit shivammathur/php/php@7.3
```
Install from source.
```zsh
brew install -s shivammathur/php/php@7.3
```

A better way would be to fork the repo, make the change and install it from your fork.

**Comment by bphmigas** [comment]
sorry.. i've follow your instruction but getting error <img width="1620" alt="image" src="https://github.com/shivammathur/homebrew-php/assets/127707886/4ea62a55-3869-4c54-aa35-a0ecaf9f51e5">

**Comment by shivammathur** [comment]
@bphmigas 
Please run `brew update`, make the change, and install from the source again. It should work now.

**Comment by bphmigas** [comment]
is something wrong? <img width="682" alt="image" src="https://github.com/shivammathur/homebrew-php/assets/127707886/284b5dad-56c8-4c3f-9800-b7c0511c3d13">

**Comment by bphmigas** [comment]
i wanna use sqlsrv & php_sqlsrv extension, and i dont want to use freetds / php_dblib
