### ISSUE TITLE
Can't build 5.6...8.0 from source

### ISSUE THREAD

**Issue by jeff-h** [shivammathur/homebrew-php#1825]
When I try to compile php 5.6, 7.2, 7.3, 7.4 and 8.0 from source I get an error. 8.1, 8.2 and 8.3 compile fine.

To be upfront I'm running Homebrew with a non-standard prefix so please just close this issue if you wish, as I understand I'm on my own with that scenario. However, your PHP formulas have worked beautifully for me for a couple of years now, so I'm hoping it's not a prefix-related issue.

An example of the error:

```
/private/tmp/phpA8.0-20230711-8017-1sjt04p/php-8.0.29/ext/openssl/openssl.c:1328:51: error: use of undeclared identifier 'RSA_SSLV23_PADDING'
        REGISTER_LONG_CONSTANT("OPENSSL_SSLV23_PADDING", RSA_SSLV23_PADDING, CONST_CS|CONST_PERSISTENT);
                                                         ^
```

https://github.com/openssl/openssl/issues/14216 suggests RSA_SSLV23_PADDING was removed from OpenSSL 3.0. Reading [the formula for 8.0](https://github.com/shivammathur/homebrew-php/blob/master/Formula/php%408.0.rb#L49), for example, shows an explicit dependency on openssl@1.1, yet the error implies it's picking up openssl@3 instead, which doesn't support RSA_SSLV23_PADDING.

Can you think of any reason it might do that, or anything I could try to resolve it? Any thoughts would be greatly appreciated!

**Comment by jeff-h** [comment]
Not sure if it's helpful (or possibly obvious)... but I just checked my previous builds (from around April) and all the PHP versions (right up to and including 8.3) have a dependency on `libssl.1.1.dylib` but the ones I *can* build successfully now depend only on `libssl.3.dylib`.

**Comment by bestplay9384** [comment]
Hello, i can confirm that issue exists. In my situation installing PHP 7.3 on Mac Os 10.15.7 (Catalina) breaks during compilation with following error:

```
Last 15 lines from /Users/my.user/Library/Logs/Homebrew/php@7.3/03.make:
      _zif_openssl_public_encrypt in openssl.o
      _zif_openssl_public_decrypt in openssl.o
  "_EVP_PKEY_size", referenced from:
      _zif_openssl_private_encrypt in openssl.o
      _zif_openssl_private_decrypt in openssl.o
      _zif_openssl_public_encrypt in openssl.o
      _zif_openssl_public_decrypt in openssl.o
      _zif_openssl_sign in openssl.o
      _zif_openssl_seal in openssl.o
  "_SSL_get_peer_certificate", referenced from:
      _php_openssl_sockop_set_option in xp_ssl.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [libs/libphp7.bundle] Error 1
make: *** Waiting for unfinished jobs....

Do not report this issue to Homebrew/brew or Homebrew/homebrew-core
```


It indicates that openssl@3 is used.

**Comment by shivammathur** [comment]
Yes, I will work on it later this weel

**Comment by jeff-h** [comment]
@shivammathur thanks so much, very grateful.

@bestplay9384 thanks for weighing in — I was very worried it was just my environment :) 

> It indicates that openssl@3 is used.

I'm curious, can you explain what told you that from the quoted logs? I also saw similar messages to those but didn't know what to make of them.

**Comment by bestplay9384** [comment]
@jeff-h yeah, error & warning log was longer :) I saw some flags provided to php compilation to provide openssl library. Then i try to uninstall any openssl version i had installed with brew already and try recompiling PHP and it occured that openssl is being installed as dependency, but in version = 3 :) I am not sure if i am right but some time ago when i was installing PHP 7.3 first time - i have seen openssl 1.1 i think, but not sure :D 

Lets just wait for @shivammathur, he knows the subject obviously the best, lets see what his invesitagion brings to us :)

**Comment by shivammathur** [comment]
@jeff-h @bestplay9384 

I have added patches and switched all formulae to use `openssl@3`. 
Please run `brew update` and build again, it should work now.

Ref: https://github.com/shivammathur/php-src-backports/commit/2bcb0bba9d3afb1c5fd5fbe5620972bef7f79f79

**Comment by jeff-h** [comment]
Just built 5.6.40_9 successfully. Am starting a few more now. Thanks for your work fixing this!

**Comment by jeff-h** [comment]
Just finished building 7.2, 7.3, 7.4 and 8.0 — everything compiled fine. Thanks again.
