### ISSUE TITLE
Php is not working

### ISSUE THREAD

**Issue by andresfdel17** [shivammathur/homebrew-php#1959]
**Describe the bug**
My php is not working 

**PHP versions**
8.2

**To Reproduce**

**Expected behavior**
My php is now not working, and don´t know the cause, till yesterday was good

**Screenshots/Logs**
<img width="1171" alt="Captura de pantalla 2023-09-09 a la(s) 10 55 15 a m" src="https://github.com/shivammathur/homebrew-php/assets/53264064/c7904ffd-fd3d-41e3-b8bf-e56ebb2e530e">
<img width="1151" alt="Captura de pantalla 2023-09-09 a la(s) 10 56 51 a m" src="https://github.com/shivammathur/homebrew-php/assets/53264064/9c2e9053-91d8-43c2-b651-440bc3903766">

**Comment by shivammathur** [comment]
@andresfdel17 

Try running `brew upgrade gd`.

If that does not solve it, please provide the output of `brew outdated`

**Comment by andresfdel17** [comment]
It's solved. Thank you very much
