### ISSUE TITLE
php 7.4 & icu4c

### ISSUE THREAD

**Issue by davidmondok** [shivammathur/homebrew-php#1977]
**Describe the bug**
When trying to run anything with php 7.4 I get this error `Library not loaded:  /usr/local/opt/icu4c/lib/libicuio.72.dylib`.

I tried reinstalling `shivammathur/php/php@7.4` after cleaning up brew first but to no avail. The latest version is linked to icu4c 72 but my installed version is icu4c 73.

**PHP versions**
7.4

I'm just wondering if I'm doing something incorrectly or that 7.4 is never going to work with icu4c 73 so it's really time to force clients to upgrade their projects to PHP 8+ which is my preferred choice anyway. But this is another good argument.

**Comment by shivammathur** [comment]
php@7.4 was rebuilt with icu `73.2` in June, 23.
Please update brew and reinstall php@7.4 and icu4c.

```zsh
brew update
brew reinstall icu4c shivammathur/php/php@7.4
```
