### ISSUE TITLE
I don't switch among version shivammathur/php 

### ISSUE THREAD

**Issue by TaiHV0211** [shivammathur/homebrew-php#1982]
**Describe the issue**
i using macos ventura 13.5.2
I install shivammathur/php 5.6, 7.1,8.0,8.1. After i switch from 7.1 to 8.1 by 
`brew services stop php@7.1`
`brew unlink php@7.1`
`brew link --overwrite --force php@8.1`
`brew services restart php@8.1`
But when i run `php --version` then result is '7.1'

**PHP versions**
7.1 - 8.1

**Expected behavior**
Switch among version php 
**Screenshots/Logs**
![image](https://github.com/shivammathur/homebrew-php/assets/72026756/8e25d0af-37f7-49b0-b6d3-a200f4c67d7b)

**Comment by shivammathur** [comment]
@TaiHV0211 

Please restart your terminal after switching and then run `php --version`

**Comment by TaiHV0211** [comment]
> @TaiHV0211
> 
> Please restart your terminal after switching and then run `php --version`

Thanks! This work

**Comment by TaiHV0211** [comment]
@shivammathur i try this but not working. i try unistall php@7.1 then have `brew unistall php@7.1' and run `rm -rf /usr/local/etc/php ` then php 8. working
