### ISSUE TITLE
How can we enable SOAP,CURL and OpenSSL Extenstions??

### ISSUE THREAD

**Issue by binumathew** [shivammathur/homebrew-php#2123]
Hey !

I uncommented soap,curl and openssl extension in the php.ini file and this is error i am getting, any idea how can i sort it out?

PHP Warning:  PHP Startup: Unable to load dynamic library 'curl' (tried: /usr/local/lib/php/pecl/20220829/curl (dlopen(/usr/local/lib/php/pecl/20220829/curl, 9): image not found), /usr/local/lib/php/pecl/20220829/curl.so (dlopen(/usr/local/lib/php/pecl/20220829/curl.so, 9): image not found)) in Unknown on line 0

Warning: PHP Startup: Unable to load dynamic library 'curl' (tried: /usr/local/lib/php/pecl/20220829/curl (dlopen(/usr/local/lib/php/pecl/20220829/curl, 9): image not found), /usr/local/lib/php/pecl/20220829/curl.so (dlopen(/usr/local/lib/php/pecl/20220829/curl.so, 9): image not found)) in Unknown on line 0
PHP Warning:  PHP Startup: Unable to load dynamic library 'openssl' (tried: /usr/local/lib/php/pecl/20220829/openssl (dlopen(/usr/local/lib/php/pecl/20220829/openssl, 9): image not found), /usr/local/lib/php/pecl/20220829/openssl.so (dlopen(/usr/local/lib/php/pecl/20220829/openssl.so, 9): image not found)) in Unknown on line 0

Warning: PHP Startup: Unable to load dynamic library 'openssl' (tried: /usr/local/lib/php/pecl/20220829/openssl (dlopen(/usr/local/lib/php/pecl/20220829/openssl, 9): image not found), /usr/local/lib/php/pecl/20220829/openssl.so (dlopen(/usr/local/lib/php/pecl/20220829/openssl.so, 9): image not found)) in Unknown on line 0
PHP Warning:  PHP Startup: Unable to load dynamic library 'soap' (tried: /usr/local/lib/php/pecl/20220829/soap (dlopen(/usr/local/lib/php/pecl/20220829/soap, 9): image not found), /usr/local/lib/php/pecl/20220829/soap.so (dlopen(/usr/local/lib/php/pecl/20220829/soap.so, 9): image not found)) in Unknown on line 0

Warning: PHP Startup: Unable to load dynamic library 'soap' (tried: /usr/local/lib/php/pecl/20220829/soap (dlopen(/usr/local/lib/php/pecl/20220829/soap, 9): image not found), /usr/local/lib/php/pecl/20220829/soap.so (dlopen(/usr/local/lib/php/pecl/20220829/soap.so, 9): image not found)) in Unknown on line 0
PHP 8.2.12 (cli) (built: Nov 12 2023 06:48:42) (NTS)
Copyright (c) The PHP Group
Zend Engine v4.2.12, Copyright (c) Zend Technologies
    with Zend OPcache v8.2.12, Copyright (c), by Zend Technologies

**Comment by shivammathur** [comment]
soap, curl, and openssl are built statically into the php binary, so you do not need to enable them in php.ini. 

Please remove entries for these extensions from php.ini, they should be loaded by default.

You can run `php -m` to check the extensions loaded.
