### ISSUE TITLE
compatibility curl and interbase

### ISSUE THREAD

**Issue by sund1** [shivammathur/homebrew-php#2139]
After brew upgrade, I get such an error when executing ibase_connect. 
Error: [error] 580#0: *17 kevent() reported about a closed connection (54: Connection reset by peer) while reading response header from upstream, client: 127.0.0.1, server: localhost, request: "GET / HTTP/1.1", upstream: "fastcgi://127.0.0.1:9073", host: "localhost".

I compiled the ibase module from https://github.com/FirebirdSQL/php-firebird. 
Also, I compiled a Firebird server (https://github.com/FirebirdSQL/firebird/issues/7041), and on version {PHP Version 7.3.33_4} everything worked perfectly. After upgrading to {PHP Version 7.3.33_8}, ibase_* started to fail on the web (php-fpm,nginx). However, everything works perfectly via terminal (php script.php). I tried to recompile ibase extension and Firebird server to new versions but it did not yield any results.
After that, I installed PHP 7.3 through macports (https://ports.macports.org/port/php73 /). I noticed that ibase_* functions only fall when the CURL module is installed.
Can I somehow disable the curl module in php@7.3? Is there any other solution to this problem?

macbook m1 pro, 13.5.1 (22G90)

<details>
  <summary>phpinfo after brew upgrade</summary>
  
  
![image](https://github.com/shivammathur/homebrew-php/assets/33967850/c0ee8448-9cf5-42b8-946c-2d056ac8e61d)
![image](https://github.com/shivammathur/homebrew-php/assets/33967850/47e2dc34-0df0-4da1-8d0c-886100c33cfd)
![image](https://github.com/shivammathur/homebrew-php/assets/33967850/0f530388-e99e-4a6c-baf7-ce0338e79c11)
  
</details>

<details>
  <summary>phpinfo before brew upgrade</summary>
  
  
![image](https://github.com/shivammathur/homebrew-php/assets/33967850/9eaa1da1-0b10-4e77-ab28-7550a8b8e5db)
![image](https://github.com/shivammathur/homebrew-php/assets/33967850/2b03b8fe-79c3-4b6f-beb9-8615e1902583)
![image](https://github.com/shivammathur/homebrew-php/assets/33967850/086acc42-7d4c-4658-afcc-26377f61cbf8)

</details>

<details>
  <summary>phpinfo macports (Curl is installed. Ibase is not functioning.)</summary>
  
  
![image](https://github.com/shivammathur/homebrew-php/assets/33967850/aea86f43-95bc-42ca-9e44-37acd7790b17)
![image](https://github.com/shivammathur/homebrew-php/assets/33967850/a8d607d3-6f39-4bf0-b001-a3306cae1060)
![image](https://github.com/shivammathur/homebrew-php/assets/33967850/b20826b9-db00-4891-aa84-75aa22579eb1)

</details>

<details>
  <summary>phpinfo macports (Curl is not installed. Ibase is functioning.)</summary>
  
  ![image](https://github.com/shivammathur/homebrew-php/assets/33967850/a906a3ed-9579-41db-88a2-317b1fbad552)

</details>

**Comment by sund1** [comment]
Found the following solution. From Formula/php@7.3.rb remove depends_on "curl" --with-curl=#{Formula["curl"].opt_prefix} and brew install shivammathur/php/php@8.3 --build-from-source
After this, compile the curl module (https://github.com/php/php-src) 
And after this, everything will work.
But there's an important detail. The brew curl version is 8.4 (and with --with-curl we get an error)
I compiled the curl module with version 8.1 (/usr/bin/curl)

**Comment by shivammathur** [comment]
This should be checked in the Firebird project.
