### ISSUE TITLE
Homebrew PHP 8.1 install: PHP dependency re2c can't find Python interpreter

### ISSUE THREAD

**Issue by zlatanG** [shivammathur/homebrew-php#2242]
Hello, I try to install php 8.1 on mac OS el Capitan
brew reinstall shivammathur/php/php@8.1

This goes well until reaching re2c:

==> Installing shivammathur/php/php@7.4 dependency: re2c

which fails with:

checking for a Python interpreter with version >= 3.7... none
configure: error: no suitable Python interpreter found

it is to be noted that python 3.9.7 is already installed in my machine : python --version 
Python 3.9.7
Thank you for your help

**Comment by shivammathur** [comment]
@zlatanG 

Unfortunately macOS El Capitan is not supported since 2019. Please consider updating to a newer supported version.
https://github.com/shivammathur/homebrew-php?tab=readme-ov-file#os-support
