### ISSUE TITLE
Brew keeps using tap shivammathur/php

### ISSUE THREAD

**Issue by marcelaerts** [shivammathur/homebrew-php#225]
Hi there,

I used your tap for testing purposes. I deleted it with the following command:
brew untap shivammathur/php

That worked. But when I try to install the default PHP from brew the tap get installed again.

I completely deleted Brew and installed it. Same result. How can this happen?

**Comment by shivammathur** [comment]
To remove this tap
```
# Remove php installed from the tap
brew ls --full-name --formula | grep '^shivammathur/php/' | xargs brew uninstall

# Remove tap
brew untap shivammathur/tap
```

Then you can install the supported php from the core tap  (currently PHP 7.3 to 8.0).
For example to install PHP 7.4
```
brew install php@7.4
```
