### ISSUE TITLE
php@8.3: Failed to download resource "php@8.3"

### ISSUE THREAD

**Issue by adjarriawan** [shivammathur/homebrew-php#2301]
curl: (22) The requested URL returned error: 401

brew install shivammathur/php/php@8.3

1. arch -arm64 brew tap shivammathur/php
2. arch -arm64 brew install shivammathur/php/php@8.3

<img width="1280" alt="Screenshot 2024-01-31 at 07 33 13" src="https://github.com/shivammathur/homebrew-php/assets/37354675/c7de29d6-9bf4-4917-a6d3-d9512481ae26">

**Comment by shivammathur** [comment]
Please run `brew update` to update the tap and then try again.

**Comment by adjarriawan** [comment]
> Please run `brew update` to update the tap and then try again.

<img width="1679" alt="Screenshot 2024-01-31 at 23 21 07" src="https://github.com/shivammathur/homebrew-php/assets/37354675/0dd43bc6-f14c-466f-a969-02bc2470339b">

Device: Macbook Air M1
OS: 14.2.1 (23C71)

**Comment by adjarriawan** [comment]
@shivammathur 

<img width="988" alt="Screenshot 2024-02-03 at 00 24 51" src="https://github.com/shivammathur/homebrew-php/assets/37354675/eafa9944-5dcb-433a-a872-cee4d9f29900">

For the repository, it is already using the latest, the error message displayed is still error code 401

**Comment by shivammathur** [comment]
It seems that there is an issue with the alias in the tap of your end. It should fetch php 8.3 from `shivammathur/php/php` package and not `shivammathur/php/php/8.3`

![image](https://github.com/shivammathur/homebrew-php/assets/1571086/636df34d-44b7-4374-8d35-f74fba320e2a)

Please remove the tap and try adding it again.

```zsh
HOMEBREW_DEVELOPER=1 brew untap shivammathur/php
brew tap shivammathur/php
```

Also make sure the brew version is the latest one using `brew update` and check that `brew doctor` does not report any issues.
