### ISSUE TITLE
PHP 7.4 and 8.0 no longer work after updating to php8.3 on Mac Sonoma (terminal using rosetta)

### ISSUE THREAD

**Issue by Gs-Joel** [shivammathur/homebrew-php#2363]
**Describe the bug**
Currently unable to install or work with php7.4 or php8.0 after updating to php8.3
Working on Mac Sonoma using terminal with Rosetta

**PHP versions**
7.4, 8.0

**To Reproduce**
brew install shivammathur/php/php@8.0
or
brew install shivammathur/php/php@7.4

**Expected behavior**
Should be able to switch to these older php versions

**Screenshots/Logs**
➜  ~ brew install shivammathur/php/php@8.0
Warning: shivammathur/php/php@8.0 has been deprecated because it is a versioned formula!
==> Downloading https://ghcr.io/v2/shivammathur/php/php/8.0/manifests/8.0.30_1-1
Already downloaded: /Users/joel/Library/Caches/Homebrew/downloads/1a8d29c64808418a99f09411aa91e8fd8caaab20c7ee94ff680cfd611212d012--php@8.0-8.0.30_1-1.bottle_manifest.json
==> Fetching shivammathur/php/php@8.0
==> Downloading https://ghcr.io/v2/shivammathur/php/php/8.0/blobs/sha256:4b2710ef9cca008c50c7a561765b95308971a3d0005c0a0977fff5203ffdc279
Already downloaded: /Users/joel/Library/Caches/Homebrew/downloads/52e83a2ad3d318c1a23c1f5df067bbeaf638016c63b33710bf3cb392b614f164--php@8.0--8.0.30_1.ventura.bottle.1.tar.gz
==> Reinstalling shivammathur/php/php@8.0 
==> Pouring php@8.0--8.0.30_1.ventura.bottle.1.tar.gz
==> /usr/local/Cellar/php@8.0/8.0.30_1/bin/pear config-set php_ini /usr/local/etc/php/8.0/php.ini system
Last 15 lines from /Users/joel/Library/Logs/Homebrew/php@8.0/post_install.01.pear:
2024-02-26 13:54:41 +0900

/usr/local/Cellar/php@8.0/8.0.30_1/bin/pear
config-set
php_ini
/usr/local/etc/php/8.0/php.ini
system

dyld[26718]: Library not loaded: /usr/local/opt/icu4c/lib/libicuio.73.dylib
  Referenced from: <FFBBB40B-7982-3E45-B925-9B5803228A71> /usr/local/Cellar/php@8.0/8.0.30_1/bin/php
  Reason: tried: '/usr/local/opt/icu4c/lib/libicuio.73.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/usr/local/opt/icu4c/lib/libicuio.73.dylib' (no such file), '/usr/local/opt/icu4c/lib/libicuio.73.dylib' (no such file), '/usr/local/lib/libicuio.73.dylib' (no such file), '/usr/lib/libicuio.73.dylib' (no such file, not in dyld cache), '/usr/local/Cellar/icu4c/74.2/lib/libicuio.73.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/usr/local/Cellar/icu4c/74.2/lib/libicuio.73.dylib' (no such file), '/usr/local/Cellar/icu4c/74.2/lib/libicuio.73.dylib' (no such file), '/usr/local/lib/libicuio.73.dylib' (no such file), '/usr/lib/libicuio.73.dylib' (no such file, not in dyld cache)
Warning: The post-install step did not complete successfully
You can try again using:
  brew postinstall shivammathur/php/php@8.0
==> Caveats
To enable PHP in Apache add the following to httpd.conf and restart Apache:
    LoadModule php_module /usr/local/opt/php@8.0/lib/httpd/modules/libphp.so

    <FilesMatch \.php$>
        SetHandler application/x-httpd-php
    </FilesMatch>

Finally, check DirectoryIndex includes index.php
    DirectoryIndex index.php index.html

The php.ini and php-fpm.ini file can be found in:
    /usr/local/etc/php/8.0/

php@8.0 is keg-only, which means it was not symlinked into /usr/local,
because this is an alternate version of another formula.

If you need to have php@8.0 first in your PATH, run:
  echo 'export PATH="/usr/local/opt/php@8.0/bin:$PATH"' >> ~/.zshrc
  echo 'export PATH="/usr/local/opt/php@8.0/sbin:$PATH"' >> ~/.zshrc

For compilers to find php@8.0 you may need to set:
  export LDFLAGS="-L/usr/local/opt/php@8.0/lib"
  export CPPFLAGS="-I/usr/local/opt/php@8.0/include"

To restart shivammathur/php/php@8.0 after an upgrade:
  brew services restart shivammathur/php/php@8.0
Or, if you don't want/need a background service you can just run:
  /usr/local/opt/php@8.0/sbin/php-fpm --nodaemonize
==> Summary
🍺  /usr/local/Cellar/php@8.0/8.0.30_1: 501 files, 77.7MB
Error: Could not remove php@8.0 backup keg! Do so manually:

**Comment by shivammathur** [comment]
Please make sure the tap is updated

```zsh
HOMEBREW_DEVELOPER=1 brew untap shivammathur/php
brew tap shivammathur/php
```

Then reinstall the PHP version to get the latest build

```zsh
brew reinstall shivammathur/php/php@8.0
```
or
```zsh
brew reinstall shivammathur/php/php@7.4
```

**Comment by marcusaaronb** [comment]
dyld[48323]: Library not loaded: /usr/local/opt/icu4c/lib/libicuio.73.dylib
  Referenced from: <8CB65B1D-E3B7-3610-AD6B-4837B5C0FEA3> /usr/local/Cellar/php@7.4/7.4.33_5/bin/php
  Reason: tried: '/usr/local/opt/icu4c/lib/libicuio.73.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/usr/local/opt/icu4c/lib/libicuio.73.dylib' (no such file), '/usr/local/opt/icu4c/lib/libicuio.73.dylib' (no such file), '/usr/local/lib/libicuio.73.dylib' (no such file), '/usr/lib/libicuio.73.dylib' (no such file, not in dyld cache), '/usr/local/Cellar/icu4c/74.2/lib/libicuio.73.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/usr/local/Cellar/icu4c/74.2/lib/libicuio.73.dylib' (no such file), '/usr/local/Cellar/icu4c/74.2/lib/libicuio.73.dylib' (no such file), '/usr/local/lib/libicuio.73.dylib' (no such file), '/usr/lib/libicuio.73.dylib' (no such file, not in dyld cache)

**Comment by marcusaaronb** [comment]
Please re-open still active

**Comment by shivammathur** [comment]
@marcusaaronb I have created PRs to rebuild with the latest icu4c formula. Should be fixed once the builds finish.

**Comment by marcusaaronb** [comment]
Thank you very much my friend :)

**Comment by marcusaaronb** [comment]
Take note 7.3 php version affected please update thanks

**Comment by shivammathur** [comment]
Please reinstall your PHP version. It should fix the icu4c issue now.
