### ISSUE TITLE
Is it possible to have full Side-by-side (SxS) installations of PHP?

### ISSUE THREAD

**Issue by rquadling** [shivammathur/homebrew-php#2436]
**Describe the feature**
To have the equivalent of a per project `.phpenv` file indicating the required version of PHP as supplied by homebrew-php, similar to how Ruby, NPM, Terraform (and I assume many others) all work, effectively bypassing/ignoring the version of PHP that would be available outside of the project.

**Underlying issue**
A developer's computer may have multiple projects on it. Using `brew-php-switcher` is good for when you are just on 1 project long term, but say you have a dozen projects, and are upgrading them. Maybe one is a library you're going to release, but another is a application that hasn't yet been upgraded and is going to be using the old version of the library. Switching PHP for any CLI based work, different extensions being available or no longer available (so a PHP 7.0 project with mcrypt usage will not run if on a later version of PHP as mcrypt is long gone).

It may be my interpretation/understanding, but it would seem that Homebrew is far better suited to server setup where 1 version of tools, libraries, and applications exist, rather than on a developer's machine where multiple versions need to exist side-by-side and be switched automatically without needing to constantly manually run a tool to flip versions.

For the TFEnv setup, the command `terraform` is actually just a proxy that loads the real required version based upon the content of the local `.tfenv` file which is actually in the VCS for the project. Suddenly any developer needing to load up a project with a different version of Terraform to what they have installed, will have it installed and off they go. No real need for the developer to do much more than have TFEnv installed.

For CLI work, I think the proxies for `php`, `pecl`, and `pear` would be relatively simple. Possible a simple script that looks from the current directory towards the root for `.phpenv` and extracts the required PHP version, translates that to a path, checks the path for the target command, and then runs it with all the supplied parameters, or runs the appropriate Homebrew installer to get the right version and then runs it (or just errors) ... that could be enough.

For php-fpm, I've not read any documentation on NOT using the current version installed by Homebrew. So, if I wanted to test the old and new versions of a project on my machine, I'm currently having to dig into the Cellar to find the paths of the versions I want to use.

**Describe alternatives**
I've used `brew-php-switcher` but it is manual and is often run after the error saying the code isn't right due to it NOT being the right version of PHP anymore.

**Additional context**
The point I want to get to is that multiple versions of PHP being installed doesn't and shouldn't mean any one version is the "right" one. It's just a tool that each project should be able to dictate the version, and for the developer to not have to flip back and forth all over the place with `brew-php-switcher`.

It may be the idea of SxS is anti-homebrew. If so, then that's sad. It may also be I've got it completely wrong and in which case I'm holding my hands up and saying "You've got me!". 

**Are you willing to submit a PR?**
I would be happy to help but would want some idea on preferred solution.

**Comment by cafferata** [comment]
@rquadling I saw your question and thought I would share my knowledge. Are you familiar with the [Symfony CLI](https://github.com/symfony-cli/symfony-cli)? This solves (among other things) the issue of PHP switching. 

There are two options:
1. `.php-version`
    https://symfony.com/doc/current/setup/symfony_server.html#selecting-a-different-php-version
2. Composer platform php configuration:
    https://getcomposer.org/doc/06-config.md#platform

Locally I have the three PHP 8.x versions installed:

```shell
symfony local:php:list
```

```shell
+---------+-------------------------------------+---------+---------------------------------+--------------------------------+---------+---------+
| Version |              Directory              |   PHP   |               PHP               |              PHP               | Server  | System? |
|         |                                     |   CLI   |               FPM               |              CGI               |         |         |
+---------+-------------------------------------+---------+---------------------------------+--------------------------------+---------+---------+
| 8.1.27  | /usr/local/Cellar/php@8.1/8.1.27_1  | bin/php | sbin/php-fpm                    | bin/php-cgi                    | PHP FPM |         |
| 8.2.16  | /usr/local/Cellar/php@8.2/8.2.16_1  | bin/php | sbin/php-fpm                    | bin/php-cgi                    | PHP FPM |         |
| 8.3.3   | /usr/local                          | bin/php | Cellar/php/8.3.3_1/sbin/php-fpm | Cellar/php/8.3.3_1/bin/php-cgi | PHP FPM | *       |
+---------+-------------------------------------+---------+---------------------------------+--------------------------------+---------+---------+

The current PHP version is selected from default version in $PATH

To control the version used in a directory, create a .php-version file that contains the version number (e.g. 7.2 or 7.2.15),
or define config.platform.php inside composer.json.
If you're using Platform.sh or Upsun, the version can also be specified in their configuration files.
```

**Example** (with `.php-version`)

```shell
mkdir project-1
echo "8.2" > project-1/.php-version
```

```shell
mkdir project-2
echo "8.3" > project-2/.php-version
```

```shell
cd project-1
symfony php -v
```
```shell
PHP 8.2.16 (cli) (built: Feb 13 2024 15:22:59) (NTS)
Copyright (c) The PHP Group
Zend Engine v4.2.16, Copyright (c) Zend Technologies
    with Zend OPcache v8.2.16, Copyright (c), by Zend Technologies
```

```shell
cd ../project-2
symfony php -v
```
```shell
PHP 8.3.3 (cli) (built: Feb 13 2024 15:41:14) (NTS)
Copyright (c) The PHP Group
Zend Engine v4.3.3, Copyright (c) Zend Technologies
    with Zend OPcache v8.3.3, Copyright (c), by Zend Technologies
```

To avoid having to think about the command `symfony php` locally, I set up an Bash alias:

```shell
#!/usr/bin/env bash
alias php='symfony php'
```

If you use Composer, you can also send this via the Symfony binary so that Composer works with the correct PHP version. Of course I have also set a local Bash alias for this:

```shell
#!/usr/bin/env bash
alias composer='symfony composer'
```

The example above also works the same when you configure PHP within Composer:

```shell
composer config platform.php "8.1"
```

I hope this helps you (or others). ☺️

**Comment by rquadling** [comment]
This was VERY interesting and immediately useful. And I think covers my requirements perfectly. As soon as I'd realised Symfony-CLI wasn't a PHP application/library!

Considering everything I needed is covered, I'm going to close this issue.

Thank you!!

**Comment by rquadling** [comment]
Oh! One word to add about all of this. The Homebrew setting of `HOMEBREW_NO_INSTALL_CLEANUP=1` is VERY VERY much needed!
