### ISSUE TITLE
Install PHP Error

### ISSUE THREAD

**Issue by phihungnv** [shivammathur/homebrew-php#245]
curl: (22) The requested URL returned error: 403 Forbidden
Error: Failed to download resource "php@7.4"
Download failed: https://dl.bintray.com/shivammathur/php/php%407.4-7.4.16.big_sur.bottle.tar.gz

**Comment by mbabker** [comment]
Looks like it's due to a brownout at Bintray - https://status.bintray.com/

**Comment by shivammathur** [comment]
@phihungnv  @mbabker 
Temporary workaround, set shivammathur/php branch to `ghcr`
```zsh
cd $(brew --repository shivammathur/php)
git fetch origin ghcr
git checkout ghcr
```

Then install PHP

After installation reset the branch back to master

```zsh
cd $(brew --repository shivammathur/php)
git checkout master
```

**Comment by shivammathur** [comment]
Fixed in https://github.com/shivammathur/homebrew-php/commit/9f4ba04dde257a2d24107fbcc93aba8b303dc3ea

**Comment by phihungnv** [comment]
@shivammathur It works now.
