### ISSUE TITLE
Install php@74 error

### ISSUE THREAD

**Issue by nicecp** [shivammathur/homebrew-php#251]
curl: (22) The requested URL returned error: 404
Error: Failed to download resource "php@7.4"
Download failed: https://ghcr.io/v2/shivammathur/php/php%407.4-7.4.16.big_sur.bottle.tar.gz

Has retaped before installing refer to [issue245](https://github.com/shivammathur/homebrew-php/issues/245)

**Comment by shivammathur** [comment]
@nicecp 

Check your brew version, it should be 3.1.1 or newer.
```bash
brew --version
```
else, Please update your brew
```
brew update
```

Then install php, if it fails again, provide the complete logs

**Comment by nicecp** [comment]
it\`s still 404...

cp@cpdeMacBook-Pro ~ % brew --version
Homebrew 3.1.2
Homebrew/homebrew-core (git revision f8462fccd0; last commit 2021-04-15)
Homebrew/homebrew-cask (git revision 1fb47889db; last commit 2021-04-15)
cp@cpdeMacBook-Pro ~ % brew install shivammathur/php/php@7.4
==> Installing php@7.4 from shivammathur/php
==> Downloading https://mirrors.ustc.edu.cn/homebrew-bottles/openssl%401.1-1.1.1k.big_sur.bottle.tar.gz
==> Downloading from https://homebrew.bintray.com/openssl@1.1-1.1.1k.big_sur.bottle.tar.gz
#=#=-#  #
curl: (22) The requested URL returned error: 404 Not Found
Trying a mirror...
==> Downloading https://ghcr.io/v2/homebrew/core/openssl%401.1-1.1.1k.big_sur.bottle.tar.gz
#=#=-#  #
curl: (22) The requested URL returned error: 404
Error: Failed to download resource "openssl@1.1"
Download failed: https://ghcr.io/v2/homebrew/core/openssl%401.1-1.1.1k.big_sur.bottle.tar.gz

**Comment by shivammathur** [comment]
ok, This is unrelated to this tap. 

`https://mirrors.ustc.edu.cn/homebrew-bottles/openssl%401.1-1.1.1k.big_sur.bottle.tar.gz` should be `https://mirrors.ustc.edu.cn/homebrew-bottles/bottles/openssl%401.1-1.1.1k.big_sur.bottle.tar.gz`.

To fix this, set your mirror correctly.
http://mirrors.ustc.edu.cn/help/homebrew-bottles.html

Set HOMEBREW_BOTTLE_DOMAIN to `https://mirrors.ustc.edu.cn/homebrew-bottles/bottles`

```zsh
export HOMEBREW_BOTTLE_DOMAIN=https://mirrors.ustc.edu.cn/homebrew-bottles/bottles
```

**Comment by nicecp** [comment]
it`s correct right now~, ths!
