### ISSUE TITLE
Mac Sonoma 14.4.1 unable to install php@7.4

### ISSUE THREAD

**Issue by oyvfhp** [shivammathur/homebrew-php#2511]
**Describe the bug**

Mac Sonoma 14.4.1 unable to install php@7.4

Error infos:
<img width="1480" alt="image" src="https://github.com/shivammathur/homebrew-php/assets/4404279/c95b20c5-e0d9-4232-95ea-06915e6e123b">

There are other errors after disabling pdo_odbc。。。

**PHP versions**

7.4

**To Reproduce**

**Expected behavior**

**Screenshots/Logs**

**Additional context**

**Are you willing to submit a PR?**

**Comment by oyvfhp** [comment]
@shivammathur  HELP！！！

**Comment by shivammathur** [comment]
I plan on addding patches for Xcode 15.3/Clang 16 next week, please wait till then.

For installing you should be able to do it without building it from the source.

**Comment by oyvfhp** [comment]
Okay, thank you very much. Looking forward to it very much

**Comment by shivammathur** [comment]
I was able to find some time today :)

Fixed in https://github.com/shivammathur/homebrew-php/commit/0b91fd267d580b013957e600bef15c40cb035784

**Comment by oyvfhp** [comment]
Wow😍, that's it. This problem has been bothering me for a few days！😁
