### ISSUE TITLE
macOS: 11.7.10-x86_64 Installing shivammathur/php/php@8.0 dependency: llvm

### ISSUE THREAD

**Issue by ryan5217** [shivammathur/homebrew-php#2552]
MacBook Pro (13-inch, 2019, Four Thunderbolt 3 ports)
macOS: 11.7.10-x86_64
HOMEBREW_VERSION: 4.2.17

brew install shivammathur/php/[php@8.0](mailto:php@8.0)
Always stuck Installing shivammathur/php/[php@8.0](mailto:php@8.0) dependency: llvm
![image](https://github.com/shivammathur/homebrew-php/assets/24778967/0cbb1d93-e057-421b-9d3c-a36601643118)

**Comment by shivammathur** [comment]
@ryan5217 

macOS 11 is not supported anymore by Apple, Homebrew and this project, please consider upgrading your OS to Monterey (12) or newer if possible.
