### ISSUE TITLE
MacOS 11 big sur not work

### ISSUE THREAD

**Issue by mglmega** [shivammathur/homebrew-php#2650]
Error: You are using macOS 11.
We (and Apple) do not provide support for this old version.
It is expected behaviour that some formulae will fail to build in this old version.
It is expected behaviour that Homebrew will be buggy and slow.
Do not create any issues about this on Homebrew's GitHub repositories.
Do not create any issues even if you think this message is unrelated.
Any opened issues will be immediately closed without response.
Do not ask for help from Homebrew or its maintainers on social media.
You may ask for help in Homebrew's discussions but are unlikely to receive a response.
Try to figure out the problem yourself and submit a fix as a pull request.
We will review it but may or may not accept it.

**Comment by shivammathur** [comment]
@mglmega 
macOS 11 is not supported anymore by Apple, Homebrew and this project, please consider upgrading your OS to Monterey (12) or newer if possible.
