### ISSUE TITLE
Patch PHP 8.1 with `ITIMER_REAL` usage for timeout handling on Apple Silicon systems

### ISSUE THREAD

**Issue by jdecool** [shivammathur/homebrew-php#2732]
**Describe the feature**

There a bug on Apple Silicon where `max_execution_time` reached too early.

This bug is described in [this issue](https://github.com/php/php-src/issues/12814) and fixed in [this PR](https://github.com/php/php-src/pull/13567) that has been merged in 8.2 & 8.3.

Because 8.1 is not maintained anymore, the fix will never be merged in this version.

Can the 8.1 (and maybe others) be dynamically patch using the Homebrew Formula ?

**Comment by shivammathur** [comment]
@jdecool Added in https://github.com/shivammathur/homebrew-php/pull/2765

**Comment by jdecool** [comment]
Awesome.

Thanks @shivammathur
