### ISSUE TITLE
php@8.1 ERROR

### ISSUE THREAD

**Issue by ningkexin** [shivammathur/homebrew-php#276]
![image](https://user-images.githubusercontent.com/17719524/116492696-7fc14000-a8cf-11eb-80c2-3619bb44a330.png)

**Comment by shivammathur** [comment]
Retap shivammathur/php
```zsh
HOMEBREW_DEVELOPER=1 brew untap shivammathur/php
brew tap shivammathur/php
```

Then install PHP
