### ISSUE TITLE
ICU4C compatibility issues

### ISSUE THREAD

**Issue by 877371623** [shivammathur/homebrew-php#2880]
When I run PHP7.4, I receive dyld [54906]: Library not loaded: '/opt/homebrew/opt/icu4c/lib/libicuio. 73. dylib';
My current version of ICU4C is 74, and the two versions are not compatible;
I tried updating brew and reinstalling it php@7.4 And icu4c：
brew update
brew reinstall icu4c shivammathur/php/ php@7.4
But it didn't solve the problem

**Comment by shivammathur** [comment]
Please run this and let me know if there are any issues
```zsh
brew doctor
```

If there are no issues in `brew doctor`, please run this again and provide me the logs

```zsh
brew update
brew reinstall icu4c shivammathur/php/php@7.4
```

**Comment by 877371623** [comment]
I uninstalled it again php@7.4 And updated the brew tap shivammathur/php;
And ICU4c has also been updated to the latest version
Afterwards, run:
brew update
brew reinstall icu4c shivammathur/php/ php@7.4
Successfully installed;
But the problem still hasn't been solved
<img width="917" alt="WeChat911aec5466ecda43cdd798b5f33997f4" src="https://github.com/shivammathur/homebrew-php/assets/68764028/22e3ff6e-033e-4aae-93c3-af6fb518fcb2">
<img width="1425" alt="WeChate0950b620c54c03688f7031ed41685e9" src="https://github.com/shivammathur/homebrew-php/assets/68764028/001ce398-eb9a-4812-9139-ca716a6611c8">
<img width="1425" alt="WeChat40508191267488a65d6f03b24aded8f6" src="https://github.com/shivammathur/homebrew-php/assets/68764028/1b891180-4f9b-44d1-9a25-b368d17dba11">

**Comment by shivammathur** [comment]
From the logs, the tap is not updated correctly as it is referencing 7.4.33_5 which is an old build. Also from brew doctor it might not be on the master branch. Please run these commands to make sure the tap is updated to latest commit on master and then try reinstalling.

```zsh
git -C $(brew --repo shivammathur/php) checkout master
git -C $(brew --repo shivammathur/php) fetch origin master
git -C $(brew --repo shivammathur/php) reset --hard origin/master
```

Then reinstall
```zsh
brew reinstall shivammathur/php/php@7.4
```

**Comment by 877371623** [comment]
The issue still persists after running the above command. I cleared all data and reinstalled it; Here are the detailed steps:
First, install shivammathur/php;

<img width="1425" alt="image" src="https://github.com/shivammathur/homebrew-php/assets/68764028/9ea68575-349e-4226-b7a0-da138f61a9da">

Then install php@7.4 Installation successful but prompts icu4c issue;
<img width="1406" alt="image" src="https://github.com/shivammathur/homebrew-php/assets/68764028/b88e06f8-4b76-4cc3-9ff9-1e9a01cc558d">
Then execute the above command to prompt that it has been updated to the latest version;

<img width="1040" alt="image" src="https://github.com/shivammathur/homebrew-php/assets/68764028/f37e37c8-c9fb-4e4e-ae3e-989722e2aa79">
Re install php@7.4 Still prompts that libicuio.73. dyslib cannot be found

<img width="1425" alt="image" src="https://github.com/shivammathur/homebrew-php/assets/68764028/559c385d-06f2-4253-a6ad-4a2cdb3646de">

**Comment by shivammathur** [comment]
If you check this image, the commit hash https://github.com/shivammathur/homebrew-php/commit/c397667 is an old commit from feb, can you try without using gitclone.com?

![image](https://github.com/shivammathur/homebrew-php/assets/1571086/7bc49461-ac41-432c-8fb1-c656384ff8ff)

```zsh
cd $(brew --repo shivammathur/php)
git remote remove origin
git remote add origin https://github.com/shivammathur/homebrew-php
git checkout master
git fetch origin master
git reset --hard origin/master
```

**Comment by 877371623** [comment]
I tried the above command but still couldn't.
I try created a new directory and pulled online projects, and checked the logs. The latest submission was also in February

<img width="1054" alt="image" src="https://github.com/shivammathur/homebrew-php/assets/68764028/a9a674e5-6ca3-4983-b4c2-cc6ae9af98cd">
<img width="959" alt="image" src="https://github.com/shivammathur/homebrew-php/assets/68764028/4a8309d8-d92d-41f2-a19d-a36484dd2069">

**Comment by 877371623** [comment]
This issue has been resolved

**Comment by jarvis657** [comment]
> From the logs, the tap is not updated correctly as it is referencing 7.4.33_5 which is an old build. Also from brew doctor it might not be on the master branch. Please run these commands to make sure the tap is updated to latest commit on master and then try reinstalling.
> 
> ```shell
> git -C $(brew --repo shivammathur/php) checkout master
> git -C $(brew --repo shivammathur/php) fetch origin master
> git -C $(brew --repo shivammathur/php) reset --hard origin/master
> ```
> 
> Then reinstall
> 
> ```shell
> brew reinstall shivammathur/php/php@7.4
> ```

thanks, this is very right
