### ISSUE TITLE
Install Failed PHP 8.0 in Ubuntu 20.04

### ISSUE THREAD

**Issue by Faisal50x** [shivammathur/homebrew-php#3]
I'm unable to install PHP 8.0 in ubuntu 20.04. 

current PHP version: 7.4.3
targeted version: 8.0

**Error Report:**

==> Installing php@8.0 from shivammathur/php
==> Downloading https://github.com/php/php-src/archive/master.tar.gz?v=php-8.0.0
Already downloaded: /home/faisal/.cache/Homebrew/downloads/954a75aab4a5895c548a1e2b5fb52b3e2c1d8a9d7e5862ba856e16d55ea24744--php-src-master.tar.gz
Warning: Cannot verify integrity of 954a75aab4a5895c548a1e2b5fb52b3e2c1d8a9d7e5862ba856e16d55ea24744--php-src-master.tar.gz
A checksum was not provided for this resource.
For your reference the SHA-256 is: 749b0aa80ba3896caafb62552636b0c3bbc26df793071cdb19970646a5fb7e61
==> Patching
patching file build/php.m4
Hunk #1 succeeded at 405 (offset -20 lines).
Hunk #2 succeeded at 450 (offset -20 lines).
patching file configure.ac
Hunk #1 succeeded at 141 (offset -49 lines).
==> ./buildconf --force
==> ./configure --prefix=/home/linuxbrew/.linuxbrew/Cellar/php@8.0/8.0.0 --local
Last 15 lines from /home/faisal/.cache/Homebrew/Logs/php@8.0/02.configure:
checking whether to enable debug assertions in release mode... no
checking whether to dlopen extensions with RTLD_NOW instead of RTLD_LAZY... no
checking layout of installed files... GNU
checking path to configuration file... /home/linuxbrew/.linuxbrew/etc/php/8.0
checking where to scan for configuration files... /home/linuxbrew/.linuxbrew/etc/php/8.0/conf.d
checking whether to enable PHP's own SIGCHLD handler... no
checking whether to explicitly link against libgcc... no
checking whether to enable short tags by default... yes
checking whether to enable dmalloc... no
checking whether to enable IPv6 support... yes
checking whether to enable DTrace support... yes
checking sys/sdt.h usability... no
checking sys/sdt.h presence... no
checking for sys/sdt.h... no
configure: error: Cannot find sys/sdt.h which is required for DTrace support

If reporting this issue please do so at (not Homebrew/brew or Homebrew/core):
  https://github.com/shivammathur/homebrew-php/issues

**Comment by shivammathur** [comment]
This is only maintained for `macOS`. To install PHP 8 on `Ubuntu`, refer to https://github.com/shivammathur/php-builder#install
