### ISSUE TITLE
php status always error at brew services

### ISSUE THREAD

**Issue by hmztraders2022** [shivammathur/homebrew-php#3049]
Hello, 
I found that the status of my php was always an error, then I have tried to stop the service then start it again.
I have repeatedly tried to uninstall then reinstall it.
I have also followed several solutions that I found, but I still haven't found the right solution.
maybe you can help me to solve this problem

like the screenshot below

<img width="765" alt="image" src="https://github.com/user-attachments/assets/3fc48d20-5b8e-496c-b558-aac760a619a3">

thanks

**Comment by shivammathur** [comment]
@hmztraders2022 

Please check the logs here `$(brew --prefix)/var/log/php-fpm.log`.

**Comment by hmztraders2022** [comment]
@shivammathur 
i found php-fpm log not found
<img width="425" alt="image" src="https://github.com/user-attachments/assets/473a55ba-a63d-447c-984c-dbdaf1ba43ce">

**Comment by shivammathur** [comment]
From the logs it looks like php-fpm.conf is missing. Please reinstall php, link it again and check that the file exists and restart the php-fpm service.

**Comment by shivammathur** [comment]
Please reopen if you are still facing the issue.

**Comment by hmztraders2022** [comment]
Ok thanks, my php 5.6 status started now, i uninstall all php at brew and
install again only 5.6
