### ISSUE TITLE
Upgrading 7.4.18 with patch included

### ISSUE THREAD

**Issue by scottperlitch** [shivammathur/homebrew-php#307]
**Describe the bug**

My hypothesis is that `brew upgrade shivammathur/php/php@7.4` is not installing the latest patch (https://github.com/shivammathur/homebrew-php/commit/fc256dac438bde6fc35e57eeeb8803c71a3f6f1a)

Running `brew upgrade shivammathur/php/php@7.4` only outputs: "Warning: shivammathur/php/php@7.4 7.4.18 already installed". Is this the expected behavior?

Is there a way to verify if the patch has been applied using phpinfo()? 

**PHP versions**

 7.4.18.

**To Reproduce**

`brew install php@7.4`
`brew upgrade shivammathur/php/php@7.4`

**Expected behavior**

The patch fixes a postgres / pdo bug. I am still seeing an error related to this bug when using Laravel Valet for development.

**Screenshots/Logs**

**Additional context**

The PHP bug that was patched: https://github.com/php/php-src/pull/6801

**Are you willing to submit a PR?**

Yes

**Comment by shivammathur** [comment]
@scottperlitch 

Reinstall using the formula from the tap. That should fix it.

```zsh
brew update
brew reinstall shivammathur/php/php@7.4
brew link --force --overwrite php@7.4
```
