### ISSUE TITLE
can't install php@7.4 the bottle for libffi

### ISSUE THREAD

**Issue by hmztraders2022** [shivammathur/homebrew-php#3113]
i got error when i install php@7.4 using brew
i try install but still can't install

<img width="1680" alt="image" src="https://github.com/user-attachments/assets/c0c98769-1f38-42c3-9ddf-d0b42edd988e">

please help,

thanks for your attention

**Comment by shivammathur** [comment]
Please report this [here](https://github.com/Homebrew/homebrew-core/issues).

**Comment by hmztraders2022** [comment]
okei, im sory for the wrong place for this issue
