### ISSUE TITLE
There is a way to install composer using for example the php version 7.4?

### ISSUE THREAD

**Issue by rmendoza83** [shivammathur/homebrew-php#3171]
This is more a question than a feature request, but I am facing this problem when I try to use composer, I am using brew to install it, but this is trying to install the latest php version on the brew repository, there is a way to install composer without to use the php version store on homebrew?

Thanks in advance for your response

Reinaldo Mendoza

**Comment by bkdotcom** [comment]
follow these instructions?

https://getcomposer.org/download/
