### ISSUE TITLE
brew upgrade shivammathur/php/php@8.4 -> not current build

### ISSUE THREAD

**Issue by bkdotcom** [shivammathur/homebrew-php#3173]
This is more of a question

How can I get the latest "nightly" or most recent Release candidate of PHP 8.4?

`brew upgrade shivammathur/php/php@8.4`

returns

php -v
PHP 8.4.0-dev (cli) (built: Sep  5 2024 00:39:00) (NTS)
Copyright (c) The PHP Group
Zend Engine v4.4.0-dev, Copyright (c) Zend Technologies
    with Xdebug v3.4.0alpha2-dev, Copyright (c) 2002-2024, by Derick Rethans
    with Zend OPcache v8.4.0-dev, Copyright (c), by Zend Technologies
    
 **on github actions latest-ubuntu I get a more recent version**
 PHP 8.4.0-dev (cli) (built: Oct 15 2024 00:31:06) (NTS)
Copyright (c) The PHP Group
Zend Engine v4.4.0-dev, Copyright (c) Zend Technologies
    with Zend OPcache v8.4.0-dev, Copyright (c), by Zend Technologies
    with Xdebug v3.4.0beta2-dev, Copyright (c) 2002-2024, by Derick Rethans
    
apparently the `E_STRICT` deprecation is fairly recent...  
https://github.com/php/php-src/commit/d313ad6098430f4e61f0121a9e7ab392d195e4e4
needing to test locally with the `E_STRICT` deprecation

Thanks

**Comment by shivammathur** [comment]
@bkdotcom Please run this instead as `brew upgrade` would only upgrade when the version changes from 8.4.0 to 8.4.1

```
brew reinstall shivammathur/php/php@8.4
```

**Comment by bkdotcom** [comment]
Brilliant!   
noted
thank you

I went the long route and did

`brew uninstall shivammathur/php/php@8.4`
`brew install shivammathur/php/php@8.4`
