### ISSUE TITLE
Versioned formula warning

### ISSUE THREAD

**Issue by jameswilddev** [shivammathur/homebrew-php#3198]
**Describe the bug**
A warning is shown when installing PHP 8.0 indicating that it is going to be withdrawn next month.  Is this true?

**PHP versions**
Depends upon project, in this case 8.0.

**To Reproduce**
```
> brew install shivammathur/php/php@8.0
Warning: shivammathur/php/php@8.0 has been deprecated because it is a versioned formula! It will be disabled on 2024-11-26.
```

**Expected behavior**
Older versions of PHP are available for upgrade work on legacy projects.

**Comment by shivammathur** [comment]
Once the support ends for a PHP version upstream, it is marked as deprecated, it will continue to work though, it just acts as a recommendation to use supported PHP versions.

https://www.php.net/supported-versions.php

**Comment by jameswilddev** [comment]
Thank you!  Bit naughty of them to say it will be "disabled".
