### ISSUE TITLE
dyld: Library not loaded: /usr/local/opt/openldap/lib/libldap-2.4.2.dylib

### ISSUE THREAD

**Issue by ningkexin** [shivammathur/homebrew-php#320]
**Describe the bug**
dyld: Library not loaded: /usr/local/opt/openldap/lib/libldap-2.4.2.dylib
  Referenced from: /usr/local/Cellar/php@7.1/7.1.33/bin/./php
  Reason: image not found
[1]    6285 abort      ./php -v

**PHP versions**
php@7.1
**To Reproduce**

**Expected behavior**

**Screenshots/Logs**
![image](https://user-images.githubusercontent.com/17719524/118227045-7254aa00-b4ba-11eb-895a-ac888159285c.png)

**Additional context**

**Are you willing to submit a PR?**

**Comment by shivammathur** [comment]
@ningkexin Rebuilding each formula, should take about an hour.

**Comment by ningkexin** [comment]
Ok, got it @shivammathur

**Comment by shivammathur** [comment]
@ningkexin 
It should work now. 
Run `brew update` and then you can reinstall PHP 7.1

```zsh
brew update
brew reinstall shivammathur/php/php@7.1
```

**Comment by ningkexin** [comment]
@shivammathur OK,It worked!
