### ISSUE TITLE
brew warning

### ISSUE THREAD

**Issue by mbunal** [shivammathur/homebrew-php#3267]
Warning: shivammathur/php/php@7.4 has been deprecated because it is deprecated upstream! It was disabled on 2023-11-28.

what will I do after 2023-11-28???

**Comment by shivammathur** [comment]
Once the support ends for a PHP version upstream, it is marked as deprecated, it will continue to work though, it just acts as a recommendation to use supported PHP versions.

https://www.php.net/supported-versions.php
