### ISSUE TITLE
brew reinstall php@8.3 gives PHP 8.4.1

### ISSUE THREAD

**Issue by exakat** [shivammathur/homebrew-php#3418]
**Describe the bug**

I run `brew reinstall php@8.3` and brew install PHP 8.4.1

**PHP versions**
PHP 8.3. All others are correct.

**To Reproduce**
`$ brew reinstall php@8.3`

It is immediately visible in the log: 
`==> Downloading https://ghcr.io/v2/shivammathur/php/php/manifests/8.4.1
Already downloaded: /Users/famille/Library/Caches/Homebrew/downloads/2bfffd6eed2370f2d5906f20431a3f5aebe459c53303d8ad4778dea8f7bbb455--php-8.4.1.bottle_manifest.json`

**Expected behavior**
I expected PHP 8.3.14 to be downloaded.

**Comment by shivammathur** [comment]
@exakat 
Please reopen if you are still facing the issue.
