### ISSUE TITLE
php 7.4.16?

### ISSUE THREAD

**Issue by sekizlipenguen** [shivammathur/homebrew-php#351]
**Describe the feature**

Hi,
how can i install this version?(7.4.16)

**Underlying issue**

**Describe alternatives**

**Additional context**

**Are you willing to submit a PR?**

**Comment by shivammathur** [comment]
You should be able to checkout the commit with PHP `7.4.16` and install it.

```
cd $(brew --repository shivammathur/php)
git checkout a8549b6
```

Then install PHP 7.4

**Comment by sekizlipenguen** [comment]
steps;
cd $(brew --repository shivammathur/php)
git checkout a8549b6
brew install shivammathur/php/php@7.4
brew link --overwrite --force php@7.4
php -v

Thanks, but I'm getting this error:

dyld: Library not loaded: /opt/homebrew/opt/openldap/lib/libldap-2.4.2.dylib
  Referenced from: /opt/homebrew/opt/php@7.4/bin/php
  Reason: image not found
zsh: abort      php -v

**Comment by sekizlipenguen** [comment]
![Screen Shot 2021-06-04 at 10 34 20](https://user-images.githubusercontent.com/36849861/120763980-6d66a180-c520-11eb-82d6-a9e3c9850309.png)
 :(

**Comment by shivammathur** [comment]
Install from source, so it builds with current library versions
```
brew reinstall -s shivammathur/php/php@7.4
```

**Comment by sekizlipenguen** [comment]
Amazing. Thanks a lot mate!

**Comment by BrianHenryIE** [comment]
This worked to install 7.4.16. Thank you.

```
cd $(brew --repository shivammathur/php)           
git checkout 4d9389bd135922e257829ef8cf49083bd091a691      
brew reinstall -s shivammathur/php/php@7.4    
```
