### ISSUE TITLE
I can't install rdkafka via pecl under the php7.1 on Mac M1

### ISSUE THREAD

**Issue by ninjachen** [shivammathur/homebrew-php#365]
**Describe the bug**
I can't install rdkafka via pecl under the php7.1 on Mac M1. Error is:  _checking build system type... Invalid configuration `arm64-apple-darwin20.5.0': machine 'arm64-apple' not recognized_

**PHP versions**
7.1

**To Reproduce**
1.  Install arm64 version homebrew 
2. Install the homebrew-php provided by you tap `shivammathur/homebrew-php` and install php@7.1 arm64
3. Install rdkafka by pecl then  meet a error

**Expected behavior**
The rdkafka will be installed by pecl success.

**Screenshots/Logs**
```checking if compiler supports -Wl,-rpath,... yes
checking build system type... Invalid configuration `arm64-apple-darwin20.5.0': machine `arm64-apple' not recognized
configure: error: /bin/sh /private/tmp/pear/temp/rdkafka/config.sub arm64-apple-darwin20.5.0 failed
ERROR: `/private/tmp/pear/temp/rdkafka/configure --with-php-config=/opt/homebrew/opt/php@7.1/bin/php-config' failed
```
Actually, I can't install any libs by pecl.

**Additional context**
I try to use `brew install memcached@7.1 --build-from-source` another extension from [shivammathur/homebrew-extensions](https://github.com/shivammathur/homebrew-extensions), and it works.

And could you fix this pecl issue ? 
Or could you please add rdkafka@7.1 into your extensions and  give some more details to help my to build and install php c extension manually?

**Comment by shivammathur** [comment]
I will add `rdkafka` to  `shivammathur/extensions` tap.

**Comment by ninjachen** [comment]
Thank you shivammathur!!
Could you give some more information to help me to understand this issue?

**Comment by shivammathur** [comment]
@ninjachen The issue is that your autoconf auxiliary file config.sub is old and does not recognize macos arm. Make sure you have the latest autoconf and Xcode cli tools, and then try again.
```zsh
brew update 
brew reinstall autoconf
brew install librdkafka
pecl download rdkafka-5.0.0
tar xf  rdkafka-5.0.0.tgz
cd rdkafka-5.0.0
phpize
./configure --with-rdkafka="$(brew --prefix librdkafka)" --with-php-config="$(which php-config)"
make
make install
```

**Comment by shivammathur** [comment]
@ninjachen Added rdkafka in [`shivammathur/extensions`](https://github.com/shivammathur/homebrew-extensions) tap.

**Comment by Mexidense** [comment]
You can use: 
`brew install shivammathur/extensions/rdkafka@PHP_VERSION`

eg: `brew install shivammathur/extensions/rdkafka@8.0`
