### ISSUE TITLE
Mcrypt PHP extension required. php@5.6

### ISSUE THREAD

**Issue by warksit** [shivammathur/homebrew-php#437]
**Describe the bug**
Receive "Mcrypt PHP extension required." when trying to run an old Laravel 4 project on php@5.6

**PHP versions**
5.6

**To Reproduce**

brew install php@5.6 then try and use mcrypt

**Expected behavior**
I understoof the mcrypt extention is installed with php@5.6

**Are you willing to submit a PR?**
Yes if i knew how to fix

**Comment by shivammathur** [comment]
@warksit 
PHP 5.6 is built with `mcrypt`, so it should be loaded by default.
Ref: https://github.com/shivammathur/homebrew-php/blob/master/Formula/php%405.6.rb#L174

Please run `php -m` to check the loaded extensions.

**Comment by warksit** [comment]
A reboot seems to have resolved the isssue, sorry
