### ISSUE TITLE
Weird results when trying to install php@7.4 on Big Sur

### ISSUE THREAD

**Issue by T2L** [shivammathur/homebrew-php#62]
**Describe the bug**
Seems like php@7.4 is broken for Big Sur; instead, it tries to install 8.0

**PHP versions**
7.4

**To Reproduce**
Run `brew install shivammathur/php/php@7.4` on a Big Sur

**Expected behavior**
PHP 7.4 should have been installed

**Screenshots/Logs**
```brew install shivammathur/php/php@7.4                                                                                                                                        ==> Installing php@7.4 from shivammathur/php
==> Downloading https://dl.bintray.com/shivammathur/php/php%407.4-8.0.0_1.big_sur.bottle.385.tar.gz
#=#=#                                                                         
curl: (22) The requested URL returned error: 404 Not Found
Error: Failed to download resource "php@7.4"
Download failed: https://dl.bintray.com/shivammathur/php/php%407.4-8.0.0_1.big_sur.bottle.385.tar.gz
Warning: Bottle installation failed: building from source.
==> Downloading https://www.php.net/distributions/php-8.0.0.tar.xz
Already downloaded: ~/Library/Caches/Homebrew/downloads/931327716c2fdbb4db0a09a404f5d0d208381bfa0ed2064764652a4f8578b4ef--php-8.0.0.tar.xz
==> Patching
==> ./buildconf --force
==> ./configure --prefix=/usr/local/Cellar/php@7.4/8.0.0_1 --localstatedir=/usr/local/var --sysconfdir=/usr/local/etc/php/8.0 --with-config-file-path=/usr/local/etc/php/8.0 --with-config-file-scan-dir=/usr/local/
==> make
```

**Additional context**
Seems like 7.3 and 8.0 works as expected, i.e 7.4 is affected 

**Are you willing to submit a PR?**
No (sorry, not sure where to look)

**Comment by T2L** [comment]
Alright, removing and adding everything helped. Sorry

**Comment by shivammathur** [comment]
Yes, you had old version of the tap and updating it using `brew update` would fetch the updated formula whenever you want to install.

**Comment by T2L** [comment]
Well, I was doing `brew update` a few times, but without any luck. Only untap/uninstall all php/cleanup/tap fixed the thing
