### ISSUE TITLE
I unable to install php on Mac os monterey

### ISSUE THREAD

**Issue by Venugopal155** [shivammathur/homebrew-php#722]
**Describe the bug**
I unable to install PHP on Mac os Monterey, getting below error
**Screenshots/Logs**
<img width="790" alt="Screenshot 2021-12-24 at 4 03 37 PM" src="https://user-images.githubusercontent.com/13997448/147345856-c7253fd5-3410-46e1-8867-7e6fcfc4481f.png">

**Comment by shivammathur** [comment]
Please provide the output of `brew tap homebrew/core`, because `httpd` is a core formula.

If there is no output, please check the core git repo and let me know the output.

```zsh
cd "$(brew --repo homebrew/core)"
git status && git show --summary
```

**Comment by cheesepipe** [comment]
This solved the same problem for me:

rm -rf $(brew --repo homebrew/core)
brew tap homebrew/core

finally follow this up with:

brew install php

**Comment by blackcore003** [comment]
@shivammathur  i am facing same issue
apple@Apples-MacBook-Pro / % brew install shivammathur/php/php@8.0
Warning: No available formula with the name "httpd" (dependency of shivammathur/php/php@8.0).
==> Searching for similarly named formulae...
Error: No similarly named formulae found.
==> Searching for a previously deleted formula (in the last month)...
Error: No previously deleted formula found.
==> Searching taps on GitHub...
Error: No formulae found in taps.


apple@Apples-MacBook-Pro / % brew tap homebrew/core
Running `brew update --preinstall`...
Error: Tap homebrew/core remote mismatch.
https://github.com/Homebrew/brew != https://github.com/Homebrew/homebrew-core


apple@Apples-MacBook-Pro / % cd "$(brew --repo homebrew/core)"
git status && git show --summary
On branch master
Your branch is up to date with 'origin/master'.

nothing to commit, working tree clean
commit 60afbd761a15bf1421cd5ce473ec7304cd9cff7d (HEAD -> master, origin/master, origin/HEAD)
Merge: 3c8fe6015 f426f1f51
Author: Mike McQuaid <mike@mikemcquaid.com>
Date:   Fri Dec 31 13:24:07 2021 +0000

    Merge pull request #12649 from neutric/update-cmd-cleanup
    
    cmd/cleanup.rb: description style tweak

apple@Apples-MacBook-Pro homebrew-core %

**Comment by shivammathur** [comment]
@blackcore003 

As the error says, the remote of your homebrew/core tap is wrong.
You can follow @cheesepipe's [comment ](https://github.com/shivammathur/homebrew-php/issues/722#issuecomment-1003130140) above to fix this.

**Comment by shivammathur** [comment]
This error is related to the core repository and not this tap. Therefore, I'm closing the issue.
