### ISSUE TITLE
Error linking php@7.2

### ISSUE THREAD

**Issue by dyenereks** [shivammathur/homebrew-php#734]
executing `brew link --force --overwrite php@7.2` or ` brew link --overwrite --force shivammathur/php/php@7.2` has below error

```
Error: Formulae found in multiple taps:
   * shivammathur/php/php@5.6
   * exolnet/deprecated/php@5.6
```

**Comment by shivammathur** [comment]
`exolnet/deprecated` tap is no longer maintained so you can remove it.

```zsh
HOMEBREW_DEVELOPER=1 brew untap exolnet/deprecated
```

Then try again.

**Comment by dyenereks** [comment]
> `exolnet/deprecated` tap is no longer maintained so you can remove it.
> 
> ```shell
> HOMEBREW_DEVELOPER=1 brew untap exolnet/deprecated
> ```
> 
> Then try again.

Works like gem, thank you 🎉
