### ISSUE TITLE
#!/usr/bin/env php got error  env: php: No such file or directory on Monterey

### ISSUE THREAD

**Issue by samsonasik** [shivammathur/homebrew-php#966]
**Describe the bug**

It seems `#!/usr/bin/env php` got error `No such file or directory` on Monterey when used on `Symfony` process.

**PHP versions**

8.1.8

**To Reproduce**

It happen on try getrector.org locally:

```bash
git clone https://github.com/rectorphp/getrector.org.git
cd getrector.org 
composer install
php -S localhost:8080 -t public
```

Additional assets data installation:

```bash
sudo npm install --global yarn
npm install
yarn run dev
```

Then, open web: http://localhost:8080/demo and click "Process"

**Expected behavior**

It should working displaying diff.

**Screenshots/Logs**

![Screen Shot 2022-07-23 at 08 45 34](https://user-images.githubusercontent.com/459648/180585745-38ec2536-1fe9-4345-9cbf-185e026dd182.png)

**Additional context**

the code for running it is on using `Symfony` Process:

```php
        $process = new Process([
            // paths for phpunit differs based on test/demo, not sure why
            \defined('PHPUNIT_COMPOSER_INSTALL') ? 'vendor/bin/rector' : '../vendor/bin/rector',
            'process',
            $analyzedFilePath,
            '--config',
            $configPath,
            '--output-format',
            'json',
        ]);

        $process->run();
```

https://github.com/rectorphp/getrector.org/blob/d95ccc9b730f177488b2dd2dc3a720df27b718c6/packages/Demo/DemoRunner.php#L82-L93

**Comment by shivammathur** [comment]
There is no issue with the tap. 
I ran a test to confirm this - https://github.com/shivammathur/test-setup-php/runs/7479134735?check_suite_focus=true#step:6:1

Please check that you installed PHP correctly.
1) Run the `env` command and check that brew's bin directory `$(brew --prefix)/bin` is in your PATH environment variable, if not add it.
2) Check that `$(brew --prefix)/bin` directory has `php` in it. If not link it again with `brew link --force --overwrite php`.

**Comment by samsonasik** [comment]
it already registered and still error:

![Screen Shot 2022-07-23 at 16 25 42](https://user-images.githubusercontent.com/459648/180599477-415661cd-677d-40f2-8983-e58c1ef0c045.png)

Also check verify in ~/.zshrc:

```bash
source ~/.bash_profile
export PATH="/opt/homebrew/opt/php/bin:$PATH"
export PATH="/opt/homebrew/opt/php/sbin:$PATH"
export PATH="/opt/homebrew/bin:$PATH"
```

**Comment by samsonasik** [comment]
it seems still error even after move the PATH export to ~/.bash_profile

```bash
➜  getrector.org git:(main) ✗ cat ~/.bash_profile 
ulimit -n 10240

export PATH=$PATH:/opt/local/bin
export PATH=$PATH:/Users/samsonasik/.composer/vendor/bin
export PATH=$PATH:/opt/homebrew/bin
export PATH=$PATH:/opt/homebrew/opt/php/bin
export PATH=$PATH:/opt/homebrew/opt/php/sbin

export GPG_TTY=$(tty)
```
