### ISSUE TITLE
Provide debug formula for PHP

### ISSUE THREAD

**Issue by alcaeus** [shivammathur/homebrew-php#972]
**Describe the feature**
Provide formulae for PHP that install with `--enable-debug`.

**Underlying issue**
When working on extensions, having debug symbols is essential for developing. In addition to that, the debug mode helps spot many other issues (such as mismatches between arginfo and zpp in functions).

**Describe alternatives**
I've previously maintained my own formulae that provide PHP versions no longer provided by homebred-core, as well as debug versions of these. However, with this repository being more complete and my time being limited, I'm looking for alternatives.

**Additional context**

**Are you willing to submit a PR?**
If there is interest to maintaining debug builds, I'd be happy to provide a PR.

**Comment by shivammathur** [comment]
I will add them this week

**Comment by shivammathur** [comment]
Closed by #976
