### ISSUE TITLE
Can't install PHP 8.1 via brew on Mac OS 10.13

### ISSUE THREAD

**Issue by webmix** [shivammathur/homebrew-php#987]
Hi there,

**Describe the bug**

Trying to install PHP 8.1 using homebrew on Mac OS 10.13.6
```
brew install shivammathur/php/php@8.1
```

It fails with the following error :
```
Error: Too many redirects (max = 25)
```
After installing again with verbose mode (-v), the logs show that a download from sourceforge actually fails :
```
==> Verifying checksum for '424ae4bff80b8e479b33c09b4e95780ed30f62dd71f215791ff07ecf7c5e5138--xzgrep-ZDI-CAN-16587.patch'
/usr/local/Homebrew/Library/Homebrew/shims/shared/curl --disable --cookie /dev/null --globoff --show-error --user-agent Homebrew/3.5.7-69-gb556db7\ \(Macintosh\;\ Intel\ Mac\ OS\ X\ 10.13.6\)\ curl/7.54.0 --header Accept-Language:\ en --retry 3 --location --silent --head --request GET https://downloads.sourceforge.net/project/lzmautils/xz-5.2.5.tar.gz
Error: Too many redirects (max = 25)
```
Tried to go to that URL and indeed it leads to a page that doesn't launch the download and constantly reloads.
Looks like the issue comes from sourceforge that hosts this archive, maybe it'd need to be hosted somewhere else ?

**PHP versions**
8.1

**Additional context**
Brew is up-to-date

**Comment by shivammathur** [comment]
`xz` comes from homebrew core tap and is not part of this project
https://github.com/Homebrew/homebrew-core/blob/master/Formula/xz.rb
We cannot change it.

Mac OS 10.13 is not supported anymore by this project as well as by homebrew core.
